import React from 'react';
import { 
  Zap, 
  Star, 
  BookOpen, 
  Layout, 
  Settings, 
  Calendar, 
  Brain, 
  Calculator,
  Shapes,
  GraduationCap,
  Home,
  Search,
  ChevronRight,
  ChevronDown,
  Link as LinkIcon,
  Sparkles,
  RefreshCw,
  Check,
  Plus,
  Printer,
  Loader2,
  Trash2,
  Edit3,
  X,
  Share2,
  Lightbulb,
  CreditCard,
  MessageSquare,
  Menu,
  HelpCircle,
  Download,
  Mail,
  Network,
  Mic,
  MicOff,
  Paperclip,
  ArrowRight,
  Target,
  BarChart3
} from 'lucide-react';

export const ICONS: Record<string, any> = {
  logo: Brain,
  star: Star,
  starSolid: Star,
  dashboard: Layout,
  planner: Calendar,
  curriculum: BookOpen,
  settings: Settings,
  math: Calculator,
  geometry: Shapes,
  education: GraduationCap,
  zap: Zap,
  home: Home,
  explore: Layout, // using Layout as fallback for explore
  assistant: HelpCircle,
  generator: CreditCard,
  myLessons: Menu,
  gallery: Layout,
  chart: BarChart3,
  search: Search,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  link: LinkIcon,
  bookOpen: BookOpen,
  sparkles: Sparkles,
  arrowPath: RefreshCw,
  check: Check,
  plus: Plus,
  printer: Printer,
  spinner: Loader2,
  trash: Trash2,
  edit: Edit3,
  close: X,
  share: Share2,
  lightbulb: Lightbulb,
  flashcards: CreditCard,
  chatBubble: MessageSquare,
  menu: Menu,
  quiz: HelpCircle,
  download: Download,
  email: Mail,
  mindmap: Network,
  microphone: Mic,
  microphoneOff: MicOff,
  paperclip: Paperclip,
  arrowRight: ArrowRight,
  target: Target,
  chartBar: BarChart3,
};

export const SUBJECTS = [
  { id: 'math', label: 'Математика', icon: ICONS.math },
  { id: 'geometry', label: 'Геометрија', icon: ICONS.geometry }
];

export const APP_NAME = "Math Curriculum AI Navigator";
