/**
 * Official MK government school registry — primary schools, secondary schools,
 * and regional vocational education/training centers. Generated by
 * scripts/generate-school-registry.mjs from scripts/data-sources/*.
 *
 * Source: https://mon.gov.mk/mk-MK/dokumenti/lista-na-aktivni-registri
 * Regenerate after updating the source files: node scripts/generate-school-registry.mjs
 */

export interface SchoolRegistryEntry {
  /** Stable slug, e.g. 'primary-042' — generated once, never reordered. */
  id: string;
  type: 'primary' | 'secondary' | 'vet';
  municipality: string;
  name: string;
  /** Absent for VET centers (only name/city/website are available in the source). */
  address?: string;
  city?: string;
  website?: string;
}

export const SCHOOL_REGISTRY: SchoolRegistryEntry[] = [
  {
    "id": "primary-001",
    "type": "primary",
    "municipality": "Аеродром",
    "name": "ОOУ „Блаже Конески“",
    "address": "ул„Венјамин Мачуковски“ бр.4"
  },
  {
    "id": "primary-002",
    "type": "primary",
    "municipality": "Аеродром",
    "name": "ООУ „Браќа Миладиновци“",
    "address": "ул „Владимир Комаров“ бр.5"
  },
  {
    "id": "primary-003",
    "type": "primary",
    "municipality": "Аеродром",
    "name": "ООУ „Димитар Македонски“",
    "address": "ул „Ѓуро Малешевац“ бр.2"
  },
  {
    "id": "primary-004",
    "type": "primary",
    "municipality": "Аеродром",
    "name": "ООУ „Гоце Делчев“ \r\n Горно Лисиче",
    "address": "ул „Горно Лисиче„ бб"
  },
  {
    "id": "primary-005",
    "type": "primary",
    "municipality": "Аеродром",
    "name": "ООУ „Ѓорѓија Пулевски“",
    "address": "Бул „Јане Сандански“ бр. 27 А"
  },
  {
    "id": "primary-006",
    "type": "primary",
    "municipality": "Аеродром",
    "name": "ООУ „Лазо Ангеловски“",
    "address": "ул „Видое Смилевски Бато“ бр.95"
  },
  {
    "id": "primary-007",
    "type": "primary",
    "municipality": "Аеродром",
    "name": "ООУ „Љубен Лапе“",
    "address": "ул. Васко Карангелески   бр. 2"
  },
  {
    "id": "primary-008",
    "type": "primary",
    "municipality": "Аеродром",
    "name": "ООУ „Александар Македонски”",
    "address": "ул.1612 бр.4"
  },
  {
    "id": "primary-009",
    "type": "primary",
    "municipality": "Арачиново",
    "name": "ООУ „Бајрам Шабани“ с.Грушино",
    "address": "ул.1, бб, с.Грушино"
  },
  {
    "id": "primary-010",
    "type": "primary",
    "municipality": "Арачиново",
    "name": "ООУ „Ѓерѓ Кастриоти Скендербеу“",
    "address": "ул. 1, бб, с.Арачиново"
  },
  {
    "id": "primary-011",
    "type": "primary",
    "municipality": "Арачиново",
    "name": "ООУ„Абдил Фрашери“",
    "address": "ул.1 бб Арачиново"
  },
  {
    "id": "primary-012",
    "type": "primary",
    "municipality": "Берово",
    "name": "ООУ „Дедо Иљо Малешевски“",
    "address": "ул. Маршал Тито, бр. 66"
  },
  {
    "id": "primary-013",
    "type": "primary",
    "municipality": "Берово",
    "name": "OОУ „Никола Петров Русински“ с.Русиново",
    "address": "ул. Борис Кидрич, бр.1, с. Русиново"
  },
  {
    "id": "primary-014",
    "type": "primary",
    "municipality": "Битола",
    "name": "Завод за рехабилитација на деца со оштетен слух, говор и глас и други проблеми во развојот „Кочо Рацин”",
    "address": "ул. Прилепска, бб"
  },
  {
    "id": "primary-015",
    "type": "primary",
    "municipality": "Битола",
    "name": "OОУ „Александар Турунџиев“ с.Кукуречани",
    "address": "с.Кукуречани"
  },
  {
    "id": "primary-016",
    "type": "primary",
    "municipality": "Битола",
    "name": "OОУ „Даме Груев“",
    "address": "ул. Ѓорче Петров, бр7"
  },
  {
    "id": "primary-017",
    "type": "primary",
    "municipality": "Битола",
    "name": "OОУ „Елпида Караманди“",
    "address": "ул. Васко Карангелески, бб"
  },
  {
    "id": "primary-018",
    "type": "primary",
    "municipality": "Битола",
    "name": "OОУ „Гоце Делчев“",
    "address": "ул. Виенска, бр.13"
  },
  {
    "id": "primary-019",
    "type": "primary",
    "municipality": "Битола",
    "name": "OОУ „Ѓорѓи Сугарев“",
    "address": "ул. Димитар Влахов, бр.32"
  },
  {
    "id": "primary-020",
    "type": "primary",
    "municipality": "Битола",
    "name": "OОУ „Св.Кирил и Методиј“",
    "address": "бул. 1-ви Мај, бр.274"
  },
  {
    "id": "primary-021",
    "type": "primary",
    "municipality": "Битола",
    "name": "OОУ „Св.Климент Охридски“",
    "address": "ул. Димче Лахчански, бб"
  },
  {
    "id": "primary-022",
    "type": "primary",
    "municipality": "Битола",
    "name": "OОУ „Коле Канински“",
    "address": "ул. Бранко Радичевиќ, б.б"
  },
  {
    "id": "primary-023",
    "type": "primary",
    "municipality": "Битола",
    "name": "OОУ „Крсте Петков Мисирков“",
    "address": "с. Бистрица,"
  },
  {
    "id": "primary-024",
    "type": "primary",
    "municipality": "Битола",
    "name": "OОУ „Стив Наумов“",
    "address": "ул. Стив Наумов, бр.93"
  },
  {
    "id": "primary-025",
    "type": "primary",
    "municipality": "Битола",
    "name": "OОУ „Тодор Ангелевски“",
    "address": "ул. Илинденска, бр. 82"
  },
  {
    "id": "primary-026",
    "type": "primary",
    "municipality": "Битола",
    "name": "OОУ „Д-р Трифун Пановски“ Битола",
    "address": "ул. Охридска, бр. 50"
  },
  {
    "id": "primary-027",
    "type": "primary",
    "municipality": "Битола",
    "name": "Државно музичко училиште -Битола",
    "address": "ул.„Булевар 1-ви Мај“ бр.110"
  },
  {
    "id": "primary-028",
    "type": "primary",
    "municipality": "Богданци",
    "name": "ООУ „Кирил и Методиј“ с.Стојаково",
    "address": "ул. Маршал Тито, бр. 60 с.Стојаково"
  },
  {
    "id": "primary-029",
    "type": "primary",
    "municipality": "Богданци",
    "name": "ООУ „Петар Мусев“",
    "address": "ул. Крушевска, бр. 64"
  },
  {
    "id": "primary-030",
    "type": "primary",
    "municipality": "Боговиње",
    "name": "ОOУ „Сами Фрашери“ с.Пирок",
    "address": "с. Пирок"
  },
  {
    "id": "primary-031",
    "type": "primary",
    "municipality": "Боговиње",
    "name": "ОOУ „Дервиш Цара“ с.Долно Палчиште",
    "address": "с. Долно Палчиште"
  },
  {
    "id": "primary-032",
    "type": "primary",
    "municipality": "Боговиње",
    "name": "ООУ „Лирија“ с.Жеровјане",
    "address": "ул. 101, бб с.Жеровјане"
  },
  {
    "id": "primary-033",
    "type": "primary",
    "municipality": "Боговиње",
    "name": "OОУ „Абдил Фрашери“ с.Боговиње",
    "address": "с. Боговиње ул. 101 бб,"
  },
  {
    "id": "primary-034",
    "type": "primary",
    "municipality": "Боговиње",
    "name": "ООУ „Сабедин Бајрами“ с.Камењане",
    "address": "ул. 101, бб, с.Камењане"
  },
  {
    "id": "primary-035",
    "type": "primary",
    "municipality": "Боговиње",
    "name": "OОУ „11 Октомври“ с.Урвич",
    "address": "с.Урвич"
  },
  {
    "id": "primary-036",
    "type": "primary",
    "municipality": "Босилово",
    "name": "ООУ „Борис Трајковски“ с.Моноспитово",
    "address": "с. Моноспитово бр. 351"
  },
  {
    "id": "primary-037",
    "type": "primary",
    "municipality": "Брвеница",
    "name": "ООУ „7 Марси“ с.Челопек",
    "address": "с.Челопек"
  },
  {
    "id": "primary-038",
    "type": "primary",
    "municipality": "Брвеница",
    "name": "ООУ „Коста Рацин“ с.Брвеница",
    "address": "ул. Браќа Стефановиќ, бб"
  },
  {
    "id": "primary-039",
    "type": "primary",
    "municipality": "Брвеница",
    "name": "ООУ „Гоце Делчев“ с.Стенче",
    "address": "с. Стенче"
  },
  {
    "id": "primary-040",
    "type": "primary",
    "municipality": "Бутел",
    "name": "ООУ„Визбегово“",
    "address": "с.Визбегово"
  },
  {
    "id": "primary-041",
    "type": "primary",
    "municipality": "Бутел",
    "name": "Јавна установа за згрижување на деца со воспитно социјални проблеми и нарушено поведение",
    "address": "ул. Петар Манџуков,бб"
  },
  {
    "id": "primary-042",
    "type": "primary",
    "municipality": "Бутел",
    "name": "ОOУ „Живко Брајковски“",
    "address": "ул. Хо Ши Мин, бб"
  },
  {
    "id": "primary-043",
    "type": "primary",
    "municipality": "Бутел",
    "name": "ОOУ „Ацо Шопов“ Радишани",
    "address": "ул. Радишанска, бр. 68а"
  },
  {
    "id": "primary-044",
    "type": "primary",
    "municipality": "Бутел",
    "name": "ОOУ „Гоце Делчев“ с.Љубанци",
    "address": "ул. 7, бр.90"
  },
  {
    "id": "primary-045",
    "type": "primary",
    "municipality": "Бутел",
    "name": "ОOУ „Климент Охридски“",
    "address": "ул. Призренска, бр.22"
  },
  {
    "id": "primary-046",
    "type": "primary",
    "municipality": "Бутел",
    "name": "ОOУ „Лиман Каба“ с.Љуботен",
    "address": "ул. 1, бр.39 с.Љуботен"
  },
  {
    "id": "primary-047",
    "type": "primary",
    "municipality": "Бутел",
    "name": "ОOУ „Панајот Гиновски“",
    "address": "ул. Ферид Бајрам, бр.30"
  },
  {
    "id": "primary-048",
    "type": "primary",
    "municipality": "Бутел",
    "name": "ОOУ „Петар Здравковски Пенко“",
    "address": "ул. II Македонска бригада, бб"
  },
  {
    "id": "primary-049",
    "type": "primary",
    "municipality": "Валандово",
    "name": "ООУ „Јосип Броз Тито“",
    "address": "ул. 6- ти Ноември, бб"
  },
  {
    "id": "primary-050",
    "type": "primary",
    "municipality": "Валандово",
    "name": "ООУ „Страшо Пинџур“ с.Јосифово",
    "address": "ул. Страшо Пинџур, бр.21/А с.Јосифово"
  },
  {
    "id": "primary-051",
    "type": "primary",
    "municipality": "Василево",
    "name": "ООУ „Гоце Делчев“ с.Василево,",
    "address": "с. Василево бр. 36"
  },
  {
    "id": "primary-052",
    "type": "primary",
    "municipality": "Василево",
    "name": "ООУ „Атанас Нивачински“ с.Нова Маала",
    "address": "с.Нова Маала"
  },
  {
    "id": "primary-053",
    "type": "primary",
    "municipality": "Вевчани",
    "name": "ООУ „Страшо Пинџур“ с.Вевчани",
    "address": "с.Вевчани"
  },
  {
    "id": "primary-054",
    "type": "primary",
    "municipality": "Велес",
    "name": "ПОУ „Маца Овчарова“",
    "address": "ул. Кресненско Востание бр.4"
  },
  {
    "id": "primary-055",
    "type": "primary",
    "municipality": "Велес",
    "name": "ООУ „Блаже Конески“",
    "address": "ул. Љубљанска бр. 1"
  },
  {
    "id": "primary-056",
    "type": "primary",
    "municipality": "Велес",
    "name": "ООУ „Панко Брашнаров“",
    "address": "ул.Кресненско востание бр.2"
  },
  {
    "id": "primary-057",
    "type": "primary",
    "municipality": "Велес",
    "name": "OОУ „Кирил и Методиј“",
    "address": "ул. Архиепископ Михаил бр.156"
  },
  {
    "id": "primary-058",
    "type": "primary",
    "municipality": "Велес",
    "name": "ОOУ „Рајко Жинзифов“ с.Горно Оризари",
    "address": "ул. Сараевска бб Горно Оризари"
  },
  {
    "id": "primary-059",
    "type": "primary",
    "municipality": "Велес",
    "name": "ООУ „Стојан Бурчевски Буридан“ с.Иванковци",
    "address": "ул. Гоце Делчев бб с.Иванковци"
  },
  {
    "id": "primary-060",
    "type": "primary",
    "municipality": "Велес",
    "name": "ООУ „Васил Главинов“",
    "address": "ул. Никола Карев бр. 2"
  },
  {
    "id": "primary-061",
    "type": "primary",
    "municipality": "Велес",
    "name": "ОМУ „Стефан Гајдов“",
    "address": "ул. Благој Нечев бр. 8"
  },
  {
    "id": "primary-062",
    "type": "primary",
    "municipality": "Велес",
    "name": "ООУ „Лирија“ с.Бузалково",
    "address": "с.Бузалково"
  },
  {
    "id": "primary-063",
    "type": "primary",
    "municipality": "Виница",
    "name": "ООУ „Гоце Делчев“",
    "address": "ул. Љупчо Сантов, бр.36"
  },
  {
    "id": "primary-064",
    "type": "primary",
    "municipality": "Виница",
    "name": "ООУ „Кочо Рацин“ с.Блатец",
    "address": "с.Блатец"
  },
  {
    "id": "primary-065",
    "type": "primary",
    "municipality": "Виница",
    "name": "ООУ „Никола Парапунов“ с.Драгобраште",
    "address": "Населено место без уличен систем бр.16 Драгобраште"
  },
  {
    "id": "primary-066",
    "type": "primary",
    "municipality": "Виница",
    "name": "ООУ „Славчо Стојменски“",
    "address": "ул. Бел Камен, бр. 7"
  },
  {
    "id": "primary-067",
    "type": "primary",
    "municipality": "Врапчиште",
    "name": "ООУ „Врапчише“ с.Врапчиште",
    "address": "с.Врапчиште"
  },
  {
    "id": "primary-068",
    "type": "primary",
    "municipality": "Врапчиште",
    "name": "ООУ „Мехмет Дерала“ с. Градец",
    "address": "ул. 101, бб с.Градец"
  },
  {
    "id": "primary-069",
    "type": "primary",
    "municipality": "Врапчиште",
    "name": "ОOУ „Сали Лиси“ с.Добридол",
    "address": "ул. 101, бб с.Добридол"
  },
  {
    "id": "primary-070",
    "type": "primary",
    "municipality": "Врапчиште",
    "name": "ООУ „Наим Фрашери“ с.Неготино",
    "address": "с.Неготино"
  },
  {
    "id": "primary-071",
    "type": "primary",
    "municipality": "Гази Баба",
    "name": "ОOУ „25 Мај“ Сингелиќ",
    "address": "ул. Алија Авдовиќ, бр.6"
  },
  {
    "id": "primary-072",
    "type": "primary",
    "municipality": "Гази Баба",
    "name": "ОOУ „Дане Крапчев“ Маџари",
    "address": "ул. Маџари, бр.9"
  },
  {
    "id": "primary-073",
    "type": "primary",
    "municipality": "Гази Баба",
    "name": "ОOУ „Григор Прличев“ Железара",
    "address": "ул. Гемиџиска, бр.57"
  },
  {
    "id": "primary-074",
    "type": "primary",
    "municipality": "Гази Баба",
    "name": "ОOУ „Кирил и Методиј“ с.Стајковци",
    "address": "ул. 6, бр.1, с. Стајковци"
  },
  {
    "id": "primary-075",
    "type": "primary",
    "municipality": "Гази Баба",
    "name": "ОOУ „Крсте Мисирков“ Маџари",
    "address": "ул. Среќко Пужалка, бр.65а"
  },
  {
    "id": "primary-076",
    "type": "primary",
    "municipality": "Гази Баба",
    "name": "ОOУ „Крум Тошев“ с.Трубарево",
    "address": "ул. 2, бр.19, с.Трубарево"
  },
  {
    "id": "primary-077",
    "type": "primary",
    "municipality": "Гази Баба",
    "name": "ОOУ „Наум Наумовски Борче“ Маџари",
    "address": "ул. Маџари, бр.25"
  },
  {
    "id": "primary-078",
    "type": "primary",
    "municipality": "Гази Баба",
    "name": "ОOУ „Наум Охридски“ с.Булачани",
    "address": "ул.5, бр.1"
  },
  {
    "id": "primary-079",
    "type": "primary",
    "municipality": "Гази Баба",
    "name": "ОOУ „Стив Наумов“ Автокоманда",
    "address": "ул. Лазар Поп Трајков, бр.28"
  },
  {
    "id": "primary-080",
    "type": "primary",
    "municipality": "Гази Баба",
    "name": "ОOУ „Вера Јоциќ“ Маџари",
    "address": "ул. Разлошка, бр.5"
  },
  {
    "id": "primary-081",
    "type": "primary",
    "municipality": "Гази Баба",
    "name": "ОOУ „Његош“ с.Јурумлери",
    "address": "ул. 2-а, бр.18, с.Јурумлери"
  },
  {
    "id": "primary-082",
    "type": "primary",
    "municipality": "Гевгелија",
    "name": "ООУ „Св.Климент Охридски“ с.Миравци",
    "address": "ул. Гоце Делчев, бр.35"
  },
  {
    "id": "primary-083",
    "type": "primary",
    "municipality": "Гевгелија",
    "name": "ООУ „Крсте Мисирков“",
    "address": "ул. Петар Мусев, бр.22"
  },
  {
    "id": "primary-084",
    "type": "primary",
    "municipality": "Гевгелија",
    "name": "ООУ „Ристо Шуклев“ с.Негорци",
    "address": "ул. Маршал Тито, бр. 22б с.Негорци"
  },
  {
    "id": "primary-085",
    "type": "primary",
    "municipality": "Гевгелија",
    "name": "ООУ „Владо Кантарџиев“",
    "address": "ул. Љубљанска, бр.4"
  },
  {
    "id": "primary-086",
    "type": "primary",
    "municipality": "Гевгелија",
    "name": "ООМУ „Васо Карајанов“",
    "address": "ул. Ристо Фаршинин,бр 41"
  },
  {
    "id": "primary-087",
    "type": "primary",
    "municipality": "Гостивар",
    "name": "ООУ „Ѓон Бузуку“ с.Србиново",
    "address": "с.Србиново"
  },
  {
    "id": "primary-088",
    "type": "primary",
    "municipality": "Гостивар",
    "name": "ООУ „Чајле“ с.Чајле",
    "address": "с.Чајле"
  },
  {
    "id": "primary-089",
    "type": "primary",
    "municipality": "Гостивар",
    "name": "ООУ „Единство-Башкими",
    "address": "ул. Панче Попоски, бр 35"
  },
  {
    "id": "primary-090",
    "type": "primary",
    "municipality": "Гостивар",
    "name": "ООУ „Фаик Коница“ с.Дебреше",
    "address": "ул. 100, бб с.Дебреше"
  },
  {
    "id": "primary-091",
    "type": "primary",
    "municipality": "Гостивар",
    "name": "ООУ „Гоце Делчев“",
    "address": "ул. Браќа Блажески, бр. 6"
  },
  {
    "id": "primary-092",
    "type": "primary",
    "municipality": "Гостивар",
    "name": "ООУ „Исмаил Ќемали“",
    "address": "ул. Ленинградска, бб"
  },
  {
    "id": "primary-093",
    "type": "primary",
    "municipality": "Гостивар",
    "name": "ООУ „Мустафа Кемал Ататурк“",
    "address": "ул. Павле Аврамоски, бр. 52"
  },
  {
    "id": "primary-094",
    "type": "primary",
    "municipality": "Гостивар",
    "name": "ООУ „Прпарими“ с.Чегране",
    "address": "с.Чегране"
  },
  {
    "id": "primary-095",
    "type": "primary",
    "municipality": "Гостивар",
    "name": "ОOУ „Форино“ с.Форино",
    "address": "с.Форино"
  },
  {
    "id": "primary-096",
    "type": "primary",
    "municipality": "Гостивар",
    "name": "ООУ „Лирија“ с.Вруток",
    "address": "с.Вруток"
  },
  {
    "id": "primary-097",
    "type": "primary",
    "municipality": "Гостивар",
    "name": "ООМУ „Енвер Стафаи“",
    "address": "ул. ЈНА бр. 371"
  },
  {
    "id": "primary-098",
    "type": "primary",
    "municipality": "Градско",
    "name": "ООУ „Даме Груев“ с.Градско",
    "address": "ул. Александар Македонски бр.68"
  },
  {
    "id": "primary-099",
    "type": "primary",
    "municipality": "Дебар",
    "name": "ООУ „Пенестиа“",
    "address": "ул. Велко Влаховиќ, бр.16"
  },
  {
    "id": "primary-100",
    "type": "primary",
    "municipality": "Дебар",
    "name": "ООУ „Ристе Ристевски“ с.Долно Костоврасти",
    "address": "с.Долно Косоврасти"
  },
  {
    "id": "primary-101",
    "type": "primary",
    "municipality": "Дебар",
    "name": "ООУ „Саид Најдени“",
    "address": "ул. Ице Ристевски, бб"
  },
  {
    "id": "primary-102",
    "type": "primary",
    "municipality": "Дебрца",
    "name": "ООУ „Дебрца“",
    "address": "с.Белчишта"
  },
  {
    "id": "primary-103",
    "type": "primary",
    "municipality": "Делчево",
    "name": "ОУ „Св.Климент Охридски“ Делчево",
    "address": "ул. Методи Митевски Брицо б.б."
  },
  {
    "id": "primary-104",
    "type": "primary",
    "municipality": "Делчево",
    "name": "ОУ „Ванчо Прке“ Делчево",
    "address": "ул. Никола Јонков Вапцаро б.б."
  },
  {
    "id": "primary-105",
    "type": "primary",
    "municipality": "Демир Капија",
    "name": "ООУ„Димче А.Габерот“",
    "address": "ул. Маршал Тито, бр.11"
  },
  {
    "id": "primary-106",
    "type": "primary",
    "municipality": "Демир Хисар",
    "name": "ООУ „Браќа Миладиновци“ с.Жван",
    "address": "с.Жван"
  },
  {
    "id": "primary-107",
    "type": "primary",
    "municipality": "Демир Хисар",
    "name": "ОOУ „Даме Груев“ с Смилево",
    "address": "с.Смилево"
  },
  {
    "id": "primary-108",
    "type": "primary",
    "municipality": "Демир Хисар",
    "name": "ОOУ „Гоце Делчев“",
    "address": "ул. Битолска, бб"
  },
  {
    "id": "primary-109",
    "type": "primary",
    "municipality": "Дојран",
    "name": "ООУ „Кочо Рацин“ Нов Дојран",
    "address": "ул. Моша Пијаде, бр.14"
  },
  {
    "id": "primary-110",
    "type": "primary",
    "municipality": "Долнени",
    "name": "ОУ „Ѓорче Петров“ с.Ропотово",
    "address": "ул. Андон Иваноски бб. с.Ропотово"
  },
  {
    "id": "primary-111",
    "type": "primary",
    "municipality": "Долнени",
    "name": "ОУ „Мирче Ацев“ с.Лажани",
    "address": "с. Лажани"
  },
  {
    "id": "primary-112",
    "type": "primary",
    "municipality": "Долнени",
    "name": "ОУ „Пецо Даскалот“ с.Долени",
    "address": "с. Долнени"
  },
  {
    "id": "primary-113",
    "type": "primary",
    "municipality": "Долнени",
    "name": "ОУ „Пере Тошев“ с.Дупјачани",
    "address": "с. Дупјачани"
  },
  {
    "id": "primary-114",
    "type": "primary",
    "municipality": "Долнени",
    "name": "ОУ „Исмаил Ќемали“ Долени",
    "address": "с. Црнилиште"
  },
  {
    "id": "primary-115",
    "type": "primary",
    "municipality": "Долнени",
    "name": "ОУ „Али Фетхи Окјар“ с.Дебреште",
    "address": "с. Дебреште"
  },
  {
    "id": "primary-116",
    "type": "primary",
    "municipality": "Долнени",
    "name": "ОУ „Лирија“ с.Житоше",
    "address": "с. Житоше"
  },
  {
    "id": "primary-117",
    "type": "primary",
    "municipality": "Ѓорче Петров",
    "name": "ООУ“Димитар Поп Георгиев Беровски",
    "address": "ул:Ѓуро Салај бр 31"
  },
  {
    "id": "primary-118",
    "type": "primary",
    "municipality": "Ѓорче Петров",
    "name": "ООУ „Ѓорче Петров“",
    "address": "ул. 4 Јули, бр.131"
  },
  {
    "id": "primary-119",
    "type": "primary",
    "municipality": "Ѓорче Петров",
    "name": "ООУ „Јоаким Крчовски“ с.Волково",
    "address": "ул.102, бб, с. Волково"
  },
  {
    "id": "primary-120",
    "type": "primary",
    "municipality": "Ѓорче Петров",
    "name": "ООУ „Мирче Ацев“",
    "address": "ул. Мечкин Камен, бр.26"
  },
  {
    "id": "primary-121",
    "type": "primary",
    "municipality": "Ѓорче Петров",
    "name": "ООУ „Страшо Пинџур“ Новоселски Пат",
    "address": "ул. Лука Геров, бр.21"
  },
  {
    "id": "primary-122",
    "type": "primary",
    "municipality": "Ѓорче Петров",
    "name": "ООУ „Тихомир Милошевски“ с.Ново Село",
    "address": "с.Ново Село"
  },
  {
    "id": "primary-123",
    "type": "primary",
    "municipality": "Желино",
    "name": "ООУ „Фан Ноли“ с.Требош",
    "address": "с. Требош, бр.101 бб"
  },
  {
    "id": "primary-124",
    "type": "primary",
    "municipality": "Желино",
    "name": "ООУ „Ибрахим Темо“ с.Стримница",
    "address": "ул.101, бр.366 с.Стримница"
  },
  {
    "id": "primary-125",
    "type": "primary",
    "municipality": "Желино",
    "name": "ООУ „Луиѓ Гуракуќи“ с.Желино",
    "address": "с. Желино"
  },
  {
    "id": "primary-126",
    "type": "primary",
    "municipality": "Желино",
    "name": "ООУ „Пашко Васа“Групчин",
    "address": "с.Групчин"
  },
  {
    "id": "primary-127",
    "type": "primary",
    "municipality": "Желино",
    "name": "ООУ „РАМЕТУЛА АМЕТИ,,ЧИФЛИК",
    "address": "с.Чифлик"
  },
  {
    "id": "primary-128",
    "type": "primary",
    "municipality": "Желино",
    "name": "ООУ „Хасан Тахсини“",
    "address": "ООУ Хасан Тахсини с.Рогле"
  },
  {
    "id": "primary-129",
    "type": "primary",
    "municipality": "Зелениково",
    "name": "ООУ„Марко Цепенков“",
    "address": "ул. 1 бр.6 ст.Зелениково"
  },
  {
    "id": "primary-130",
    "type": "primary",
    "municipality": "Зрновци",
    "name": "ОУ „Синиша Стоилов“",
    "address": "ул. Ѓенерал Апостолски б.б."
  },
  {
    "id": "primary-131",
    "type": "primary",
    "municipality": "Илинден",
    "name": "ООУ „Браќа Миладиновци“ с.Миладиновци",
    "address": "с.Миладиновци"
  },
  {
    "id": "primary-132",
    "type": "primary",
    "municipality": "Илинден",
    "name": "ООУ „Гоце Делчев“",
    "address": "ул. 9, бр.179, Илинден"
  },
  {
    "id": "primary-133",
    "type": "primary",
    "municipality": "Илинден",
    "name": "ООУ „Ристо Крле“ с.Кадино",
    "address": "ул. 10 бр. 34г, с. Кадино"
  },
  {
    "id": "primary-134",
    "type": "primary",
    "municipality": "Јегуновце",
    "name": "ОOУ „Шемшево“ с.Шемшево",
    "address": "с.Шемшово"
  },
  {
    "id": "primary-135",
    "type": "primary",
    "municipality": "Јегуновце",
    "name": "ООУ „Симче Настовски“ с.Вратница",
    "address": "с.Вратница"
  },
  {
    "id": "primary-136",
    "type": "primary",
    "municipality": "Јегуновце",
    "name": "ОOУ „Александар Здравковски“ с.Јегуновце",
    "address": "с.Јегуновце"
  },
  {
    "id": "primary-137",
    "type": "primary",
    "municipality": "Кaвадарци",
    "name": "ОOУ „Димката Ангелов- Габерот“ с.Ваташа",
    "address": "ул. Страшо Пинџур, бр.186 с.Ваташа"
  },
  {
    "id": "primary-138",
    "type": "primary",
    "municipality": "Кaвадарци",
    "name": "ООУ ,,Димката Ангелов Габерот“",
    "address": "ул. Браќа Хаџи Тефови, бр. 40"
  },
  {
    "id": "primary-139",
    "type": "primary",
    "municipality": "Кaвадарци",
    "name": "ООУ „Гоце Делчев“",
    "address": "бул.Цветан Димов, бр.1"
  },
  {
    "id": "primary-140",
    "type": "primary",
    "municipality": "Кaвадарци",
    "name": "ООУ „Страшо Пинџур“",
    "address": "ул. Димката Ангелов Габерот, бр.3"
  },
  {
    "id": "primary-141",
    "type": "primary",
    "municipality": "Кaвадарци",
    "name": "OОУ „Тошо Велков Пепето“",
    "address": "ул. Димката Ангелов, бб. 27"
  },
  {
    "id": "primary-142",
    "type": "primary",
    "municipality": "Кaвадарци",
    "name": "ООУ „Тоде Хаџи Тефов“",
    "address": "ул. Пионерска, бр.24"
  },
  {
    "id": "primary-143",
    "type": "primary",
    "municipality": "Кaвадарци",
    "name": "ООМБУ „Лазо Мицев-Рале“",
    "address": "ул. Браќа Миладиновци, бб"
  },
  {
    "id": "primary-144",
    "type": "primary",
    "municipality": "Карбинци",
    "name": "ООУ „Страшо Пинџур“ с.Карбинци",
    "address": "с.Карбинци"
  },
  {
    "id": "primary-145",
    "type": "primary",
    "municipality": "Карпош",
    "name": "ООУ „Аврам Писевски“ с.Бардовци",
    "address": "ул. 2, бр. 10 с. Бардовци"
  },
  {
    "id": "primary-146",
    "type": "primary",
    "municipality": "Карпош",
    "name": "ООУ „Братство“ Тафталиџе",
    "address": "ул. Московска, бр.18"
  },
  {
    "id": "primary-147",
    "type": "primary",
    "municipality": "Карпош",
    "name": "ООУ „Димо Хаџи Димов“ Влае",
    "address": "ул. Ангел Динев, бр.5"
  },
  {
    "id": "primary-148",
    "type": "primary",
    "municipality": "Карпош",
    "name": "ООУ „Христијан Тодоровски Карпош“",
    "address": "ул. Орце Николов, бр.161"
  },
  {
    "id": "primary-149",
    "type": "primary",
    "municipality": "Карпош",
    "name": "ООУ „Јан Амос Коменски“, Тафталиџе",
    "address": "ул. Варшавска бр.23"
  },
  {
    "id": "primary-150",
    "type": "primary",
    "municipality": "Карпош",
    "name": "ООУ „Лазо Трповски“",
    "address": "ул. Радика бр.9"
  },
  {
    "id": "primary-151",
    "type": "primary",
    "municipality": "Карпош",
    "name": "ООУ „Петар Поп Арсов“",
    "address": "ул. Трифун Бузев бб"
  },
  {
    "id": "primary-152",
    "type": "primary",
    "municipality": "Карпош",
    "name": "ООУ „Вера Циривири Трена“",
    "address": "ул. Руѓер Бошковиќ бр.9"
  },
  {
    "id": "primary-153",
    "type": "primary",
    "municipality": "Карпош",
    "name": "ООУ „Владо Тасевски“",
    "address": "ул. Миле Поп Јорданов бр.74"
  },
  {
    "id": "primary-154",
    "type": "primary",
    "municipality": "Карпош",
    "name": "ООУ „Војдан Чернодрински“ Тафталиџе",
    "address": "ул. Дрезденска, бр. 3"
  },
  {
    "id": "primary-155",
    "type": "primary",
    "municipality": "Кисела Вода",
    "name": "ООУ „Кирил Пејчиновиќ“",
    "address": "ул. Пушкинова, бр.17"
  },
  {
    "id": "primary-156",
    "type": "primary",
    "municipality": "Кисела Вода",
    "name": "ООУ „Климент Охридски“ с.Драчево",
    "address": "ул. Јустинијан Први, бр.98"
  },
  {
    "id": "primary-157",
    "type": "primary",
    "municipality": "Кисела Вода",
    "name": "ООУ „Круме Кепески“",
    "address": "ул. Сава Ковачевиќ бр. 76"
  },
  {
    "id": "primary-158",
    "type": "primary",
    "municipality": "Кисела Вода",
    "name": "ООУ „Кузман Шапкарев“ населба Драчево",
    "address": "ул. Антон Димитров, бр.135"
  },
  {
    "id": "primary-159",
    "type": "primary",
    "municipality": "Кисела Вода",
    "name": "ООУ „Кузман Јосифовски Питу“",
    "address": "ул. Aнтон Попов, бр. 2"
  },
  {
    "id": "primary-160",
    "type": "primary",
    "municipality": "Кисела Вода",
    "name": "ООУ „Невена Георгиева Дуња“",
    "address": "ул. Михаил Чаков, бр.2"
  },
  {
    "id": "primary-161",
    "type": "primary",
    "municipality": "Кисела Вода",
    "name": "ООУ „Партенија Зографски“",
    "address": "ул. Доситеј Обрадовиќ, бр.18"
  },
  {
    "id": "primary-162",
    "type": "primary",
    "municipality": "Кисела Вода",
    "name": "ООУ „Рајко Жинзифов“ Драчево",
    "address": "ул. Иван Хаџиниколов, бр.2"
  },
  {
    "id": "primary-163",
    "type": "primary",
    "municipality": "Кисела Вода",
    "name": "ПОУ „Д-р Златан Сремец“ Скопје",
    "address": "ул. Емил Зола, бр.5"
  },
  {
    "id": "primary-164",
    "type": "primary",
    "municipality": "Кисела Вода",
    "name": "Завод Димитар Влахов",
    "address": "ул. Ѓорѓи Димитров, бб"
  },
  {
    "id": "primary-165",
    "type": "primary",
    "municipality": "Кичево",
    "name": "ОУ „Кузман Јосифовски Питу“",
    "address": "ул. 4-ти Јули, бр.59"
  },
  {
    "id": "primary-166",
    "type": "primary",
    "municipality": "Кичево",
    "name": "ОУ „Санде Штрејоски“",
    "address": "ул.11 Септември, бр.143"
  },
  {
    "id": "primary-167",
    "type": "primary",
    "municipality": "Кичево",
    "name": "ООУ „Д-р Владимир Полежиноски“",
    "address": "ул. Арсо Војвода, бб"
  },
  {
    "id": "primary-168",
    "type": "primary",
    "municipality": "Кичево",
    "name": "ОУ „Христо Узунов“ с.Другово",
    "address": "ул. Гоце Делчев бр.31 с. Другово"
  },
  {
    "id": "primary-169",
    "type": "primary",
    "municipality": "Кичево",
    "name": "ООУ „Ѓерѓ Кастриоти Скендербеу“ с.Србица",
    "address": "с.Србица"
  },
  {
    "id": "primary-170",
    "type": "primary",
    "municipality": "Кичево",
    "name": "ООУ „Милто Ѓура“ с.Стрелци",
    "address": "с.Стрелци"
  },
  {
    "id": "primary-171",
    "type": "primary",
    "municipality": "Кичево",
    "name": "ОУ „Наим Фрашери“ с.Јагол Доленци",
    "address": "с.Јагол Доленци"
  },
  {
    "id": "primary-172",
    "type": "primary",
    "municipality": "Кичево",
    "name": "ОУ „Фаик Коница“ с.Грешница",
    "address": "с.Грешница"
  },
  {
    "id": "primary-173",
    "type": "primary",
    "municipality": "Кичево",
    "name": "ОУ „Реџо Рушит Зајази“ с.Зајас",
    "address": "с.Зајас"
  },
  {
    "id": "primary-174",
    "type": "primary",
    "municipality": "Конче",
    "name": "ОOУ „Гоце Делчев“ с.Конче",
    "address": "с. Конче"
  },
  {
    "id": "primary-175",
    "type": "primary",
    "municipality": "Кочани",
    "name": "ООУ „Св.Кирил и Методиј“",
    "address": "ул. Глигор Апостолов - Гочо, бр.33"
  },
  {
    "id": "primary-176",
    "type": "primary",
    "municipality": "Кочани",
    "name": "ООУ „Крсте Петков Мисирков“ с.Оризари",
    "address": "ул. Маршал Тито, бр. 20 с.Оризари"
  },
  {
    "id": "primary-177",
    "type": "primary",
    "municipality": "Кочани",
    "name": "ООУ „Малина Попиванова“ Кочани",
    "address": "ул.Тодосије Паунов, бр.95"
  },
  {
    "id": "primary-178",
    "type": "primary",
    "municipality": "Кочани",
    "name": "ООУ „Никола Карев“",
    "address": "ул. Никола Карев, бр.17"
  },
  {
    "id": "primary-179",
    "type": "primary",
    "municipality": "Кочани",
    "name": "ООУ „Раде Кратовче“ Кочани",
    "address": "ул. Борис Трајковски, бр. 42"
  },
  {
    "id": "primary-180",
    "type": "primary",
    "municipality": "Кочани",
    "name": "ОМУ „Ристо Јурков“",
    "address": "ул. Љупчо Сантов, бб"
  },
  {
    "id": "primary-181",
    "type": "primary",
    "municipality": "Кратово",
    "name": "ОУ „Кочо Рацин“ Кратово",
    "address": "ул. Михаило Апостолски бр.11"
  },
  {
    "id": "primary-182",
    "type": "primary",
    "municipality": "Крива Паланка",
    "name": "ООУ „Илинден“",
    "address": "ул. Наско Тамбурков, бр. 80"
  },
  {
    "id": "primary-183",
    "type": "primary",
    "municipality": "Крива Паланка",
    "name": "ОOУ „Јоаким Крчовски“",
    "address": "ул. Св.Јоаким Осоговски, бр.139"
  },
  {
    "id": "primary-184",
    "type": "primary",
    "municipality": "Кривогаштани",
    "name": "ОУ „Јонче Смугрески“ с.Обршани",
    "address": "ул.Стибера бр.49"
  },
  {
    "id": "primary-185",
    "type": "primary",
    "municipality": "Кривогаштани",
    "name": "ООУ „Манчу Матак“ с.Кривогаштани",
    "address": "ул. Едвард Кардељ бр.9"
  },
  {
    "id": "primary-186",
    "type": "primary",
    "municipality": "Крушево",
    "name": "ОУ „Св.Кирил и Методиј“ с.Бучин",
    "address": "с. Бучин"
  },
  {
    "id": "primary-187",
    "type": "primary",
    "municipality": "Крушево",
    "name": "ООУ „Никола Карев“ Крушево",
    "address": "ул. Шула Мина бр.6а"
  },
  {
    "id": "primary-188",
    "type": "primary",
    "municipality": "Куманово",
    "name": "ООУ „11 Октомври“",
    "address": "ул. Тодор Велков, бб"
  },
  {
    "id": "primary-189",
    "type": "primary",
    "municipality": "Куманово",
    "name": "ООУ „Бајрам Шабани“",
    "address": "ул. Карл Маркс, бр. 52"
  },
  {
    "id": "primary-190",
    "type": "primary",
    "municipality": "Куманово",
    "name": "ООУ „Браќа Миладиновци“",
    "address": "ул. Народна Револуција, бр.43"
  },
  {
    "id": "primary-191",
    "type": "primary",
    "municipality": "Куманово",
    "name": "ООУ „Браќа Рибар“ с.Табановце",
    "address": "с.Табановце"
  },
  {
    "id": "primary-192",
    "type": "primary",
    "municipality": "Куманово",
    "name": "ООУ „Јероним Дерада“ с.Черкез",
    "address": "с.Черкез"
  },
  {
    "id": "primary-193",
    "type": "primary",
    "municipality": "Куманово",
    "name": "ООУ „Карпош“ с.Умин Дол",
    "address": "с.Умин Дол"
  },
  {
    "id": "primary-194",
    "type": "primary",
    "municipality": "Куманово",
    "name": "ООУ „Кирил и Методиј“ с.Романовце",
    "address": "с.Романовце"
  },
  {
    "id": "primary-195",
    "type": "primary",
    "municipality": "Куманово",
    "name": "ООУ „Кочо Рацин“ Куманово",
    "address": "ул. Никшиќка, бб"
  },
  {
    "id": "primary-196",
    "type": "primary",
    "municipality": "Куманово",
    "name": "ООУ „Крсте Мисирков“",
    "address": "ул. Народна револуција, бб. 43"
  },
  {
    "id": "primary-197",
    "type": "primary",
    "municipality": "Куманово",
    "name": "ООУ „Магдалена Антова“ с.Крапош",
    "address": "ул. 110, бр.5"
  },
  {
    "id": "primary-198",
    "type": "primary",
    "municipality": "Куманово",
    "name": "ООУ „Битолски Конгрес“ с.Лопате",
    "address": "с.Лопате"
  },
  {
    "id": "primary-199",
    "type": "primary",
    "municipality": "Куманово",
    "name": "ООУ „Наим Фрашери“",
    "address": "ул. Наим Фрашери, бб"
  },
  {
    "id": "primary-200",
    "type": "primary",
    "municipality": "Куманово",
    "name": "ООУ „Толи Зордумис“",
    "address": "ул. Боро Прцан, бр.38"
  },
  {
    "id": "primary-201",
    "type": "primary",
    "municipality": "Куманово",
    "name": "ООУ „Вера Которка“ с.Клечовце",
    "address": "Населено место без уличен систем с.Клечевце"
  },
  {
    "id": "primary-202",
    "type": "primary",
    "municipality": "Куманово",
    "name": "ООУ „Вук Караџиќ“ Куманово",
    "address": "ул. Браќа Филиповиќ, бр.17"
  },
  {
    "id": "primary-203",
    "type": "primary",
    "municipality": "Куманово",
    "name": "ООУ „Христијан Карпош“",
    "address": "ул. Радоје Димиќ, бб"
  },
  {
    "id": "primary-204",
    "type": "primary",
    "municipality": "Куманово",
    "name": "ОМУ „Панче Пешев“ Куманово",
    "address": "ул. Братство Единство, бр.1"
  },
  {
    "id": "primary-205",
    "type": "primary",
    "municipality": "Липково",
    "name": "ООУ „Дитурија“",
    "address": "с. Липково"
  },
  {
    "id": "primary-206",
    "type": "primary",
    "municipality": "Липково",
    "name": "ООУ„Култура“ с.Матејче",
    "address": "с. Матејче"
  },
  {
    "id": "primary-207",
    "type": "primary",
    "municipality": "Липково",
    "name": "OOУ„Антон Зако Чајупи“ с.Отља",
    "address": "с.Отља"
  },
  {
    "id": "primary-208",
    "type": "primary",
    "municipality": "Липково",
    "name": "ООУ„7 Марси“ с.Опае",
    "address": "с.Опае"
  },
  {
    "id": "primary-209",
    "type": "primary",
    "municipality": "Липково",
    "name": "ООУ„Фаик Коница“ с.Слупчане",
    "address": "с.Слупчане"
  },
  {
    "id": "primary-210",
    "type": "primary",
    "municipality": "Липково",
    "name": "ООУ„5 Октомври“ с.Никуштак",
    "address": "с.Никуштак"
  },
  {
    "id": "primary-211",
    "type": "primary",
    "municipality": "Липково",
    "name": "ООУ„Рилиндја“ с.Љојане",
    "address": "с.Љојане"
  },
  {
    "id": "primary-212",
    "type": "primary",
    "municipality": "Лозово",
    "name": "ОOУ „Методи Митевски-Брицо“ Лозово",
    "address": "ул. Маршал Тито б.б."
  },
  {
    "id": "primary-213",
    "type": "primary",
    "municipality": "Маврово и Ростуше",
    "name": "OОУ „Хајан Селмани“ с. Ростуше",
    "address": "с.Ростуше"
  },
  {
    "id": "primary-214",
    "type": "primary",
    "municipality": "Маврово и Ростуше",
    "name": "ООУ „Блаже Конески“ с.Скидриње",
    "address": "с. Скудриње"
  },
  {
    "id": "primary-215",
    "type": "primary",
    "municipality": "Маврово и Ростуше",
    "name": "ОOУ „Денче Дејаноски“ с.Маврови Анови",
    "address": "с.Маврови Анови"
  },
  {
    "id": "primary-216",
    "type": "primary",
    "municipality": "Маврово и Ростуше",
    "name": "ООУ „Јосип Броз Тито“ с.Жеровница",
    "address": "с. Жировница"
  },
  {
    "id": "primary-217",
    "type": "primary",
    "municipality": "Македонска Kaменица",
    "name": "ОOУ „Св.Кирил и Методиј“",
    "address": "ул. Маршал Тито, бр. 2"
  },
  {
    "id": "primary-218",
    "type": "primary",
    "municipality": "Македонски Брод",
    "name": "ООУ „Св.Климент Охридски“",
    "address": "ул. Партизанска, бр.33"
  },
  {
    "id": "primary-219",
    "type": "primary",
    "municipality": "Могила",
    "name": "ООУ „Браќа Миладиновци“ с.Добрушево",
    "address": "с.Добрушево"
  },
  {
    "id": "primary-220",
    "type": "primary",
    "municipality": "Могила",
    "name": "ООУ „Кочо Рацин“ с.Ивањевци",
    "address": "с. Ивањевци"
  },
  {
    "id": "primary-221",
    "type": "primary",
    "municipality": "Могила",
    "name": "ООУ „Гоце Делчев“",
    "address": "ул. Димче Могилчe бр.93 с. Могила"
  },
  {
    "id": "primary-222",
    "type": "primary",
    "municipality": "Неготино",
    "name": "ООУ„Гоце Делчев“",
    "address": "ул. Маршал Тито, бр.117"
  },
  {
    "id": "primary-223",
    "type": "primary",
    "municipality": "Неготино",
    "name": "ООУ„Страшо Пинџур“",
    "address": "ул. Партизанска, бр.146"
  },
  {
    "id": "primary-224",
    "type": "primary",
    "municipality": "Неготино",
    "name": "ООМУ„Владимир Арсовски“",
    "address": "ул.Маршал Тито, бр.102"
  },
  {
    "id": "primary-225",
    "type": "primary",
    "municipality": "Новаци",
    "name": "ООУ „Славко Лумбарковски“",
    "address": "с.Новаци"
  },
  {
    "id": "primary-226",
    "type": "primary",
    "municipality": "Ново Село",
    "name": "ПОУ „Св.Климент Охридски”",
    "address": "ул. Маршал Тито, бр.103"
  },
  {
    "id": "primary-227",
    "type": "primary",
    "municipality": "Ново Село",
    "name": "ООУ „Видое Подгорец“ с.Колешино",
    "address": "с. Колешино бр. 88"
  },
  {
    "id": "primary-228",
    "type": "primary",
    "municipality": "Ново Село",
    "name": "ООУ „Мануш Турновски“",
    "address": "ул.„Климент Охридски“ бр.4, 2434 Ново Село"
  },
  {
    "id": "primary-229",
    "type": "primary",
    "municipality": "Охрид",
    "name": "ООУ,,Живко Чинго,, с. Велгошти",
    "address": "с. Велгошти"
  },
  {
    "id": "primary-230",
    "type": "primary",
    "municipality": "Охрид",
    "name": "ООУ „Братство Единство“",
    "address": "ул. 7 Ноември, бр.85"
  },
  {
    "id": "primary-231",
    "type": "primary",
    "municipality": "Охрид",
    "name": "ООУ„Григор Прличев“",
    "address": "ул. Димитар Влахов, бр.65"
  },
  {
    "id": "primary-232",
    "type": "primary",
    "municipality": "Охрид",
    "name": "ООУ„Христо Узунов“",
    "address": "ул. Даме Груев,бр.128"
  },
  {
    "id": "primary-233",
    "type": "primary",
    "municipality": "Охрид",
    "name": "ООУ„Св. Климент Охридски“",
    "address": "ул. Климентов Универзитет, бб"
  },
  {
    "id": "primary-234",
    "type": "primary",
    "municipality": "Охрид",
    "name": "ООУ „Кочо Рацин“",
    "address": "ул.130, бр.24"
  },
  {
    "id": "primary-235",
    "type": "primary",
    "municipality": "Охрид",
    "name": "ООУ „ Св. Наум Охридски“ с.Пештани",
    "address": "с.Пештани"
  },
  {
    "id": "primary-236",
    "type": "primary",
    "municipality": "Охрид",
    "name": "ООУ „Ванчо Николески“ с.Лескоец",
    "address": "с.Лескоец"
  },
  {
    "id": "primary-237",
    "type": "primary",
    "municipality": "Охрид",
    "name": "ОМУ „Методи Патче“",
    "address": "ул. Никола Карев бр.4"
  },
  {
    "id": "primary-238",
    "type": "primary",
    "municipality": "Петровец",
    "name": "ООУ „Братство-Единство“ с.Средно Коњари",
    "address": "с.Средно Коњари ул. 1 бр. 1"
  },
  {
    "id": "primary-239",
    "type": "primary",
    "municipality": "Петровец",
    "name": "ООУ „Кочо Рацин“",
    "address": "ул.1, бр.185"
  },
  {
    "id": "primary-240",
    "type": "primary",
    "municipality": "Пехчево",
    "name": "OОУ „Ванчо Китанов“",
    "address": "ул. Дамјан Груев бр.1"
  },
  {
    "id": "primary-241",
    "type": "primary",
    "municipality": "Пласница",
    "name": "ООУ„Мустафа Кемал Ататурк“",
    "address": "с.Пласница"
  },
  {
    "id": "primary-242",
    "type": "primary",
    "municipality": "Пласница",
    "name": "ООУ „Јунус Емре“ с.Лисичани",
    "address": "с.Лисичани"
  },
  {
    "id": "primary-243",
    "type": "primary",
    "municipality": "Прилеп",
    "name": "ООУ„Страшо Пинџур“ с. Мало Коњари",
    "address": "с. Мало Коњари"
  },
  {
    "id": "primary-244",
    "type": "primary",
    "municipality": "Прилеп",
    "name": "ООУ„Блаже Конески“",
    "address": "ул. Самоилова, бр. 15"
  },
  {
    "id": "primary-245",
    "type": "primary",
    "municipality": "Прилеп",
    "name": "ООУ„Добре Јованоски“",
    "address": "ул.11 Октомври, бр.143"
  },
  {
    "id": "primary-246",
    "type": "primary",
    "municipality": "Прилеп",
    "name": "ООУ„Гоце Делчев“",
    "address": "ул. Мечкин Камен, бр.2"
  },
  {
    "id": "primary-247",
    "type": "primary",
    "municipality": "Прилеп",
    "name": "ООУ„Кире Гаврилоски-Јане“",
    "address": "ул. Јоска Јорданоски, бр.46"
  },
  {
    "id": "primary-248",
    "type": "primary",
    "municipality": "Прилеп",
    "name": "ООУ„Кирил и Методиј“ с. Канатларци",
    "address": "с. Канатларци"
  },
  {
    "id": "primary-249",
    "type": "primary",
    "municipality": "Прилеп",
    "name": "ООУ„Кочо Рацин“",
    "address": "ул. Борка Талески, бр.64"
  },
  {
    "id": "primary-250",
    "type": "primary",
    "municipality": "Прилеп",
    "name": "OOУ „Климент Охридски“",
    "address": "ул. Ленин, бб"
  },
  {
    "id": "primary-251",
    "type": "primary",
    "municipality": "Прилеп",
    "name": "ООУ„Круме Волнароски“ с.Тополчани",
    "address": "ул. Маршал Тито, бр.6, с.Тополчани"
  },
  {
    "id": "primary-252",
    "type": "primary",
    "municipality": "Прилеп",
    "name": "ООУ „Рампо Левката“",
    "address": "ул. Цар Самоил, бр.1а"
  },
  {
    "id": "primary-253",
    "type": "primary",
    "municipality": "Прилеп",
    "name": "ООМУ„Ордан Михајлосkи-Оцка“",
    "address": "ул. Орде Тутески, бр.19"
  },
  {
    "id": "primary-254",
    "type": "primary",
    "municipality": "Пробиштип",
    "name": "ОУ „Браќа Миладиновци“ Пробиштип",
    "address": "ул. Гоце Делчев бр.2"
  },
  {
    "id": "primary-255",
    "type": "primary",
    "municipality": "Пробиштип",
    "name": "ОУ „Никола Карев“ Пробиштип",
    "address": "ѕ"
  },
  {
    "id": "primary-256",
    "type": "primary",
    "municipality": "Радовиш",
    "name": "ОУ „Кирил и Методиј“ с.Ораовица",
    "address": "с. Ораовица"
  },
  {
    "id": "primary-257",
    "type": "primary",
    "municipality": "Радовиш",
    "name": "ОУ „Коста Рацин“ с.Подареш, Радовиш",
    "address": "с. Подареш"
  },
  {
    "id": "primary-258",
    "type": "primary",
    "municipality": "Радовиш",
    "name": "ОУ „Крсте Петков Мисирков“ Радовиш",
    "address": "бул. Александар Македонски б.б."
  },
  {
    "id": "primary-259",
    "type": "primary",
    "municipality": "Радовиш",
    "name": "ОУ „Никола Карев“ Радовиш",
    "address": "ул. Илинденска б.б."
  },
  {
    "id": "primary-260",
    "type": "primary",
    "municipality": "Радовиш",
    "name": "ОУ „Орце Николов“ с.Ињево, Радовиш",
    "address": "с. Ињево"
  },
  {
    "id": "primary-261",
    "type": "primary",
    "municipality": "Ранковце",
    "name": "ОУ „Христијан Тодоровски Карпош“ с.Ранковце",
    "address": "с. Ранковце"
  },
  {
    "id": "primary-262",
    "type": "primary",
    "municipality": "Ресен",
    "name": "ОУ „Браќа Миладиновци“ с.Царев Двор",
    "address": "ул. Царев Двор"
  },
  {
    "id": "primary-263",
    "type": "primary",
    "municipality": "Ресен",
    "name": "ОУ „Димитар Влахов“ с.Љубојно",
    "address": "с.Љубојно"
  },
  {
    "id": "primary-264",
    "type": "primary",
    "municipality": "Ресен",
    "name": "ОУ „Гоце Делчев“ Ресен",
    "address": "ул. Мите Трповски бр.30"
  },
  {
    "id": "primary-265",
    "type": "primary",
    "municipality": "Ресен",
    "name": "ОУ „Мите Богоевски“ Ресен",
    "address": "ул. 29-ти ноември бр.213"
  },
  {
    "id": "primary-266",
    "type": "primary",
    "municipality": "Ресен",
    "name": "ОУ „Славејко Арсов“ с.Подмочани",
    "address": "с. Подмочани"
  },
  {
    "id": "primary-267",
    "type": "primary",
    "municipality": "Росоман",
    "name": "ООУ „Пере Тошев“",
    "address": "ул. Пере Тошев, бр.2"
  },
  {
    "id": "primary-268",
    "type": "primary",
    "municipality": "Сарај",
    "name": "ООУ „Бајрам Шабани“ с.Кондово",
    "address": "с.Кондово"
  },
  {
    "id": "primary-269",
    "type": "primary",
    "municipality": "Сарај",
    "name": "ООУ „Дитуриа“",
    "address": "ул. 4, бр.105"
  },
  {
    "id": "primary-270",
    "type": "primary",
    "municipality": "Сарај",
    "name": "OОУ „Дрита“ с.Рашче",
    "address": "с.Рашче"
  },
  {
    "id": "primary-271",
    "type": "primary",
    "municipality": "Сарај",
    "name": "ООУ „Емин Дураку“ с.Буковиќ",
    "address": "с.Буковиќ"
  },
  {
    "id": "primary-272",
    "type": "primary",
    "municipality": "Сарај",
    "name": "ООУ „Фаик Коница“ с.Радуша",
    "address": "с.Радуша"
  },
  {
    "id": "primary-273",
    "type": "primary",
    "municipality": "Сарај",
    "name": "ООУ „Ибе Паликуќа“ с.Бојане",
    "address": "с.Бојане"
  },
  {
    "id": "primary-274",
    "type": "primary",
    "municipality": "Сарај",
    "name": "ООУ „Сами Фрашери“ с.Глумово",
    "address": "с.Глумово"
  },
  {
    "id": "primary-275",
    "type": "primary",
    "municipality": "Сарај",
    "name": "ООУ „Бедри Таири“ с.Долно Свиларе"
  },
  {
    "id": "primary-276",
    "type": "primary",
    "municipality": "Сарај",
    "name": "ООУ Перпарими- Крушопек",
    "address": "ул.1 бр.161 Крушопек"
  },
  {
    "id": "primary-277",
    "type": "primary",
    "municipality": "Свети Николе",
    "name": "ООУ „Даме Груев“ с.Ерџелија",
    "address": "ул. Маршал Тито бр.31 с.Ерџелија"
  },
  {
    "id": "primary-278",
    "type": "primary",
    "municipality": "Свети Николе",
    "name": "OОУ „Гоце Делчев“ Свети Николе",
    "address": "ул.Цветан Димов бр. 57"
  },
  {
    "id": "primary-279",
    "type": "primary",
    "municipality": "Свети Николе",
    "name": "OОУ „Кирил и Методиј“ Свети Николе",
    "address": "ул. Ангел Трајчев бр.40"
  },
  {
    "id": "primary-280",
    "type": "primary",
    "municipality": "Сопиште",
    "name": "ООУ „Драга Стојанова“ с.Ракотинци",
    "address": "ул. 1, бр.2А с.Ракотинци"
  },
  {
    "id": "primary-281",
    "type": "primary",
    "municipality": "Сопиште",
    "name": "ООУ„Дитурија“ с.Чифлик",
    "address": "с.Чифлик"
  },
  {
    "id": "primary-282",
    "type": "primary",
    "municipality": "Старо Нагоричане",
    "name": "ООУ„Светозар Маркович“",
    "address": "с. Старо Нагоричане"
  },
  {
    "id": "primary-283",
    "type": "primary",
    "municipality": "Старо Нагоричане",
    "name": "ООУ„Христијан Карпош“ с.Младо Нагоричане",
    "address": "с.Младо Нагоричане"
  },
  {
    "id": "primary-284",
    "type": "primary",
    "municipality": "Старо Нагоричане",
    "name": "ООУ„Христијан Тодоровски Карпош“ с.Драгоманце",
    "address": "с.Драгоманце"
  },
  {
    "id": "primary-285",
    "type": "primary",
    "municipality": "Струга",
    "name": "ООУ „Ашим Агуши“ с.Радолишта",
    "address": "с. Радолишта"
  },
  {
    "id": "primary-286",
    "type": "primary",
    "municipality": "Струга",
    "name": "ООУ „Браќа Миладиновци“",
    "address": "ул. Јово Стефаноски-Риле бр.4"
  },
  {
    "id": "primary-287",
    "type": "primary",
    "municipality": "Струга",
    "name": "ООУ „Единство“ с.Октиси",
    "address": "с. Октиси"
  },
  {
    "id": "primary-288",
    "type": "primary",
    "municipality": "Струга",
    "name": "ООУ „Гоце Делчев“ с.Јабланица",
    "address": "с. Јабланица"
  },
  {
    "id": "primary-289",
    "type": "primary",
    "municipality": "Струга",
    "name": "ООУ „Гоце Делчев“ с.Подгорци",
    "address": "с. Подгорци"
  },
  {
    "id": "primary-290",
    "type": "primary",
    "municipality": "Струга",
    "name": "ООУ „Јосип Броз Тито“",
    "address": "Ул. Димче Ковачески, бр. 64"
  },
  {
    "id": "primary-291",
    "type": "primary",
    "municipality": "Струга",
    "name": "ООУ „Климент Охридски“ с.Драслајца",
    "address": "с. Драслајца"
  },
  {
    "id": "primary-292",
    "type": "primary",
    "municipality": "Струга",
    "name": "ООУ „Мурат Лабуништа“ Лабуништа",
    "address": "с. Лабуништа"
  },
  {
    "id": "primary-293",
    "type": "primary",
    "municipality": "Струга",
    "name": "ООУ „Нури Мазари“ с.Делогожда",
    "address": "с. Делогожда"
  },
  {
    "id": "primary-294",
    "type": "primary",
    "municipality": "Струга",
    "name": "ООУ „Орхан Џемаили“\r\n с.Горно Татеши",
    "address": "с.Горно Татеши"
  },
  {
    "id": "primary-295",
    "type": "primary",
    "municipality": "Струга",
    "name": "ООУ „Зини Хани“ с.Велешта",
    "address": "с.Велешта"
  },
  {
    "id": "primary-296",
    "type": "primary",
    "municipality": "Струга",
    "name": "ООМУ „Струга“",
    "address": "ул.Наум Наумовски Борче бб Струга"
  },
  {
    "id": "primary-297",
    "type": "primary",
    "municipality": "Струмица",
    "name": "Завод Бања Банско",
    "address": "Бања Банско бб"
  },
  {
    "id": "primary-298",
    "type": "primary",
    "municipality": "Струмица",
    "name": "ОOУ „Даме Груев“ с.Кукулиш",
    "address": "с.Куклиш бр. 99"
  },
  {
    "id": "primary-299",
    "type": "primary",
    "municipality": "Струмица",
    "name": "ОOУ „Герас Цунев“ с.Просениково",
    "address": "с.Просениково бр. 80"
  },
  {
    "id": "primary-300",
    "type": "primary",
    "municipality": "Струмица",
    "name": "ОOУ „Гоце Делчев“ с.Вељуса",
    "address": "с.Вељуса"
  },
  {
    "id": "primary-301",
    "type": "primary",
    "municipality": "Струмица",
    "name": "ОOУ „Св. Кирил и Методиј“ с.Дабиље",
    "address": "с.Дабиљe бр.360"
  },
  {
    "id": "primary-302",
    "type": "primary",
    "municipality": "Струмица",
    "name": "ООУ „Маршал Тито“",
    "address": "ул. Кирил и Методиј, бр. 26"
  },
  {
    "id": "primary-303",
    "type": "primary",
    "municipality": "Струмица",
    "name": "ООУ „Маршал Тито“ с.Муртино",
    "address": "с. Муртино бр. 297"
  },
  {
    "id": "primary-304",
    "type": "primary",
    "municipality": "Струмица",
    "name": "ООУ „Никола Вапцаров“",
    "address": "ул. Ценка Павлова, бр.1"
  },
  {
    "id": "primary-305",
    "type": "primary",
    "municipality": "Струмица",
    "name": "ООУ „Сандо Масев“",
    "address": "ул. Моша Пијаде, бр. 8"
  },
  {
    "id": "primary-306",
    "type": "primary",
    "municipality": "Струмица",
    "name": "ООУ „Видое Подгорец“",
    "address": "ул. 1 Мај, бр. 34"
  },
  {
    "id": "primary-307",
    "type": "primary",
    "municipality": "Струмица",
    "name": "ОМУ „Боро Џони“",
    "address": "ул. Ѓорѓи Трајков бб"
  },
  {
    "id": "primary-308",
    "type": "primary",
    "municipality": "Студеничани",
    "name": "ООУ „Алија Авдовиќ“ с.Батинци",
    "address": "с. Батинци без уличен систем"
  },
  {
    "id": "primary-309",
    "type": "primary",
    "municipality": "Студеничани",
    "name": "OОУ„Наим Фрашери”",
    "address": "С.Студеничани"
  },
  {
    "id": "primary-310",
    "type": "primary",
    "municipality": "Студеничани",
    "name": "ООУ „Мустафа Кемал Ататурк“ Долно Количани",
    "address": "Долно Количани бб"
  },
  {
    "id": "primary-311",
    "type": "primary",
    "municipality": "Теарце",
    "name": "ООУ „Екрем Чабеј“ с.Слатино",
    "address": "ул. 103 бр. 6, с. Слатино"
  },
  {
    "id": "primary-312",
    "type": "primary",
    "municipality": "Теарце",
    "name": "ООУ „Фаик Коница“ с.Доброште",
    "address": "с.Доброште"
  },
  {
    "id": "primary-313",
    "type": "primary",
    "municipality": "Теарце",
    "name": "ООУ „Исмаил Ќемали“ с.Нераште",
    "address": "с.Теарце"
  },
  {
    "id": "primary-314",
    "type": "primary",
    "municipality": "Теарце",
    "name": "ООУ „Кирил Пејчиновиќ“ с.Теарце",
    "address": "с.Теарце"
  },
  {
    "id": "primary-315",
    "type": "primary",
    "municipality": "Теарце",
    "name": "ООУ „Асдрени“ с.Глоѓ",
    "address": "с.Глоѓи"
  },
  {
    "id": "primary-316",
    "type": "primary",
    "municipality": "Тетово",
    "name": "ООУ „Андреја Савевски Ќиќиш“",
    "address": "ул.Иво Рибар Лола бр.46 Тетово"
  },
  {
    "id": "primary-317",
    "type": "primary",
    "municipality": "Тетово",
    "name": "ООУ „Братство Миѓени“",
    "address": "ул. Љубе Божиновски Пиш, бр. 41"
  },
  {
    "id": "primary-318",
    "type": "primary",
    "municipality": "Тетово",
    "name": "ООУ „Ѓерѓ Кастриоти Скендербег“ с.Порој",
    "address": "с.Порој"
  },
  {
    "id": "primary-319",
    "type": "primary",
    "municipality": "Тетово",
    "name": "ООУ „Гоце Делчев“",
    "address": "ул. Иво Рибар Лола, бр. 96"
  },
  {
    "id": "primary-320",
    "type": "primary",
    "municipality": "Тетово",
    "name": "ООУ „Истикбал“",
    "address": "ул. Браќа Миладинови, бр.85"
  },
  {
    "id": "primary-321",
    "type": "primary",
    "municipality": "Тетово",
    "name": "ООУ „Кирил и Методиј“",
    "address": "ул. Видое Смилевски Бато, бб"
  },
  {
    "id": "primary-322",
    "type": "primary",
    "municipality": "Тетово",
    "name": "ООУ „Лирија“",
    "address": "ул. Дервиш Цара, бр. 6"
  },
  {
    "id": "primary-323",
    "type": "primary",
    "municipality": "Тетово",
    "name": "ООУ „Наим Фрашери“",
    "address": "ул. 113, бр. 7"
  },
  {
    "id": "primary-324",
    "type": "primary",
    "municipality": "Тетово",
    "name": "ООУ „Беса“ с.Мала Речица",
    "address": "Мала Речица"
  },
  {
    "id": "primary-325",
    "type": "primary",
    "municipality": "Тетово",
    "name": "ООУ „Перпарими“ с.Речица",
    "address": "с. Голема Речица"
  },
  {
    "id": "primary-326",
    "type": "primary",
    "municipality": "Тетово",
    "name": "ООУ „Реџеп Вока“ с.Шипковица",
    "address": "с. Шипковица"
  },
  {
    "id": "primary-327",
    "type": "primary",
    "municipality": "Тетово",
    "name": "ООУ „Рилиндја“ с.Селце, Тетово",
    "address": "с.Селце"
  },
  {
    "id": "primary-328",
    "type": "primary",
    "municipality": "Тетово",
    "name": "ДМУ Тодор Скаловски-Тетоец Тетово",
    "address": "ул.Иво Рибар Лола 118"
  },
  {
    "id": "primary-329",
    "type": "primary",
    "municipality": "Центар",
    "name": "ОOУ „11 Октомври“",
    "address": "ул. Мирче Ацев, бр.102"
  },
  {
    "id": "primary-330",
    "type": "primary",
    "municipality": "Центар",
    "name": "ОOУ „Димитар Миладинов“",
    "address": "ул. Кочо Рацин, бр.17"
  },
  {
    "id": "primary-331",
    "type": "primary",
    "municipality": "Центар",
    "name": "ОOУ „Гоце Делчев“",
    "address": "ул. Градски ѕид, бр.34"
  },
  {
    "id": "primary-332",
    "type": "primary",
    "municipality": "Центар",
    "name": "ОOУ „Јохан Хајнрих Песталоци“",
    "address": "ул. Апостол Гусларот, бр.3"
  },
  {
    "id": "primary-333",
    "type": "primary",
    "municipality": "Центар",
    "name": "ОOУ „Св.Кирил и Методиј“",
    "address": "ул.1737, бр.1"
  },
  {
    "id": "primary-334",
    "type": "primary",
    "municipality": "Центар",
    "name": "ОOУ „Кочо Рацин“",
    "address": "ул. Салвадор Аљенде, бр.2"
  },
  {
    "id": "primary-335",
    "type": "primary",
    "municipality": "Центар",
    "name": "ОOУ „Коле Неделковски“",
    "address": "ул. Антоние Грубишиќ, бр.8"
  },
  {
    "id": "primary-336",
    "type": "primary",
    "municipality": "Центар",
    "name": "ОOУ„Киро Глигоров“",
    "address": "„ул. Aдам Мицкиевиќ “ бр.14, Центар, Скопје"
  },
  {
    "id": "primary-337",
    "type": "primary",
    "municipality": "Центар",
    "name": "ДМБУЦ „Илија Николовски Луј”",
    "address": "ул. Црвена Скопска Општина, бр.4"
  },
  {
    "id": "primary-338",
    "type": "primary",
    "municipality": "Центар Жупа",
    "name": "ОOУ „Мустафа Кемал Ататурк“ Центaр Жупа",
    "address": "Центар Жупа"
  },
  {
    "id": "primary-339",
    "type": "primary",
    "municipality": "Центар Жупа",
    "name": "ОOУ „Неџати Зекирија“ с.Коџаџик, Центaр Жупа",
    "address": "с.Коџаџик"
  },
  {
    "id": "primary-340",
    "type": "primary",
    "municipality": "Чаир",
    "name": "ОOУ „Васил Главинов“ Чаир",
    "address": "ул.Џон Кенеди б.б."
  },
  {
    "id": "primary-341",
    "type": "primary",
    "municipality": "Чаир",
    "name": "ОOУ „Хасан Приштина“ Чаир",
    "address": "ул. Коста Абрашевиќ бр.7"
  },
  {
    "id": "primary-342",
    "type": "primary",
    "municipality": "Чаир",
    "name": "ОOУ „7 Марси“ Чаир",
    "address": "ул. Коста Абрашевиќ бр.3"
  },
  {
    "id": "primary-343",
    "type": "primary",
    "municipality": "Чаир",
    "name": "ОOУ „Јашар Беј Шкупи“ Чаир,",
    "address": "ул. 124 Дуќанџик бр.б.б."
  },
  {
    "id": "primary-344",
    "type": "primary",
    "municipality": "Чаир",
    "name": "ООУ „Лириа“ Чаир",
    "address": "ул. Цветан Димов бр.94"
  },
  {
    "id": "primary-345",
    "type": "primary",
    "municipality": "Чаир",
    "name": "ОOУ „Конгреси и Манастирит“ Чаир",
    "address": "ул. Петре Георгиев бр.22"
  },
  {
    "id": "primary-346",
    "type": "primary",
    "municipality": "Чаир",
    "name": "OОУ „Тефејјуз“ Чаир",
    "address": "ул. Чаирска бр.2"
  },
  {
    "id": "primary-347",
    "type": "primary",
    "municipality": "Чаир",
    "name": "ОOУ „Имри Елези“ Чаир",
    "address": "ул. Браќа Реџепагиќ б.б."
  },
  {
    "id": "primary-348",
    "type": "primary",
    "municipality": "Чаир",
    "name": "ОOУ „Исмаил Ќемали“ Чаир",
    "address": "ул. Методија Митевски б.б."
  },
  {
    "id": "primary-349",
    "type": "primary",
    "municipality": "Чаир",
    "name": "OOУ„ А.С.Макаренко“",
    "address": "ул.Џон Кенеди бр.32"
  },
  {
    "id": "primary-350",
    "type": "primary",
    "municipality": "Чаир",
    "name": "ОУ за возрасни „Антон Семјонович Макаренко“ Чаир",
    "address": "ул.Џон Кенеди бр.32"
  },
  {
    "id": "primary-351",
    "type": "primary",
    "municipality": "Чаир",
    "name": "ПОУ,, Иднина“",
    "address": "ул.2 Македонска Бригада, бр.3 Општина Чаир"
  },
  {
    "id": "primary-352",
    "type": "primary",
    "municipality": "Чашка",
    "name": "ООУ „Петар Поп Арсов“ с.Богомила",
    "address": "с.Богомила"
  },
  {
    "id": "primary-353",
    "type": "primary",
    "municipality": "Чашка",
    "name": "ООУ „Тодор Јанев“ с.Чашка",
    "address": "ул. 8 - ми Септември, бр.1"
  },
  {
    "id": "primary-354",
    "type": "primary",
    "municipality": "Чашка",
    "name": "ООУ „Лирија“",
    "address": "с.Горно Јаболчиште"
  },
  {
    "id": "primary-355",
    "type": "primary",
    "municipality": "Чешиново Облешево",
    "name": "ОУ „Климент Охридски“ с.Облешево",
    "address": "ул. Маршал Тито бр. 29"
  },
  {
    "id": "primary-356",
    "type": "primary",
    "municipality": "Чешиново Облешево",
    "name": "ОУ „Страшо Пинџур“ с.Соколарци",
    "address": "ул. Маршал Тито бр.4"
  },
  {
    "id": "primary-357",
    "type": "primary",
    "municipality": "Чучер Сандево",
    "name": "ООУ „Александар Урдаревски“ с.Сандево",
    "address": "ул. 1, бр.11 с.Сандево"
  },
  {
    "id": "primary-358",
    "type": "primary",
    "municipality": "Чучер Сандево",
    "name": "ООУ „Св.Кирил и Методиј“ с.Кучевиште",
    "address": "ул. 8, бр.57 с.Кучевиште"
  },
  {
    "id": "primary-359",
    "type": "primary",
    "municipality": "Чучер Сандево",
    "name": "ООУ „Михаљ Грамено“ с.Брест",
    "address": "с.Брест"
  },
  {
    "id": "primary-360",
    "type": "primary",
    "municipality": "Штип",
    "name": "ООУ „Димитар Влахов“",
    "address": "ул. Сремски фронт, бб"
  },
  {
    "id": "primary-361",
    "type": "primary",
    "municipality": "Штип",
    "name": "ООУ „Гоце Делчев“",
    "address": "ул. Иво Лола Рибар, бр.179"
  },
  {
    "id": "primary-362",
    "type": "primary",
    "municipality": "Штип",
    "name": "ООУ „Тошо Арсов“",
    "address": "бул. ЈНА, бб"
  },
  {
    "id": "primary-363",
    "type": "primary",
    "municipality": "Штип",
    "name": "ООУ „Ванчо Прке“",
    "address": "ул. Васил Главинов, бб"
  },
  {
    "id": "primary-364",
    "type": "primary",
    "municipality": "Штип",
    "name": "ООУ „Славејко Арсов“",
    "address": "ул. Крушевска Република, бр.68"
  },
  {
    "id": "primary-365",
    "type": "primary",
    "municipality": "Штип",
    "name": "ДМУ „Сергеј Михајлов“",
    "address": "ул. Рајко Жинзифов, бб"
  },
  {
    "id": "primary-366",
    "type": "primary",
    "municipality": "Шуто Оризари",
    "name": "ООУ „26 Јули“ Шуто Оризари",
    "address": "ул. Индира Ганди, бр.31"
  },
  {
    "id": "primary-367",
    "type": "primary",
    "municipality": "Шуто Оризари",
    "name": "ООУ „Браќа Рамиз Хамид“ Шуто Оризари",
    "address": "ул. Че Гевара, бр.80"
  },
  {
    "id": "secondary-001",
    "type": "secondary",
    "municipality": "Берово",
    "name": "ОСУ „Ацо Русковски“",
    "address": "ул. „Даме Груев“ бб, Берово"
  },
  {
    "id": "secondary-002",
    "type": "secondary",
    "municipality": "Битола",
    "name": "СОУ Гимназија „Јосип Броз Тито“",
    "address": "бул. „1-ви мај“ бр.51, Битола"
  },
  {
    "id": "secondary-003",
    "type": "secondary",
    "municipality": "Битола",
    "name": "СОТУ „Ѓорѓи  Наумов“",
    "address": "ул. „Партизанска“ бб, Битола"
  },
  {
    "id": "secondary-004",
    "type": "secondary",
    "municipality": "Битола",
    "name": "СОУ „Таки Даскало“",
    "address": "ул. „Борис Кидрич“ бб, Битола"
  },
  {
    "id": "secondary-005",
    "type": "secondary",
    "municipality": "Битола",
    "name": "СОЕУ „Јане Сандански“",
    "address": "бул. „1-ви Мај“ бр.59, Битола"
  },
  {
    "id": "secondary-006",
    "type": "secondary",
    "municipality": "Битола",
    "name": "СОЗУ „Кузман Шапкарев“",
    "address": "ул. „Прилепска“ бб, Битола"
  },
  {
    "id": "secondary-007",
    "type": "secondary",
    "municipality": "Битола",
    "name": "ОСМУ „Д-р Јован Калаузи“",
    "address": "ул. „Иво Лола Рибар“ бр. 31 б, Битола"
  },
  {
    "id": "secondary-008",
    "type": "secondary",
    "municipality": "Битола",
    "name": "Државно музичко училиште",
    "address": "бул. „1-ви Мај“ бр.110, Битола"
  },
  {
    "id": "secondary-009",
    "type": "secondary",
    "municipality": "Богданци",
    "name": "СОУ „Богданци“",
    "address": "ул. „Маршал Тито“ бб, Богданци"
  },
  {
    "id": "secondary-010",
    "type": "secondary",
    "municipality": "Валандово",
    "name": "ОСУ „Гоце Делчев“",
    "address": "ул. „Првомајска“ бр.3, Валандово"
  },
  {
    "id": "secondary-011",
    "type": "secondary",
    "municipality": "Велес",
    "name": "СОУ Гимназија„Кочо Рацин“",
    "address": "ул. „Благој Ѓорев“ бб, Велес"
  },
  {
    "id": "secondary-012",
    "type": "secondary",
    "municipality": "Велес",
    "name": "ОСУ „Јовче Тесличков“",
    "address": "ул. „Иво Лола Рибар“ бр.2, Велес"
  },
  {
    "id": "secondary-013",
    "type": "secondary",
    "municipality": "Велес",
    "name": "ССОУ „Коле Неделковски“",
    "address": "ул. „Андон Шурков“ бр.4, Велес"
  },
  {
    "id": "secondary-014",
    "type": "secondary",
    "municipality": "Велес",
    "name": "ССОУ „Димитрија Чуповски“",
    "address": "ул. „Благој Ѓорев“ бб, Велес"
  },
  {
    "id": "secondary-015",
    "type": "secondary",
    "municipality": "Велес",
    "name": "СОУ „Ванчо Прке“",
    "address": "ул. „Димитар Влахов“ бр.2, Виница"
  },
  {
    "id": "secondary-016",
    "type": "secondary",
    "municipality": "Врапчиште",
    "name": "СОУ „Неготино“",
    "address": "с. Неготино, Врапчиште"
  },
  {
    "id": "secondary-017",
    "type": "secondary",
    "municipality": "Гевгелија",
    "name": "СОУ „Јосиф Јосифовски“",
    "address": "ул. „Македонија“ бр.1, Гевгелија"
  },
  {
    "id": "secondary-018",
    "type": "secondary",
    "municipality": "Гостивар",
    "name": "СОУ „Гостивар“",
    "address": "ул. „Ристо Оџаклиески“ бб, Гостивар"
  },
  {
    "id": "secondary-019",
    "type": "secondary",
    "municipality": "Гостивар",
    "name": "ОСТУ „Гостивар“",
    "address": "ул. „Борис Кидрич“ бр.167, Гостивар"
  },
  {
    "id": "secondary-020",
    "type": "secondary",
    "municipality": "Гостивар",
    "name": "СЕОУ „Гостивар“",
    "address": "ул. „Живко Брајковски“ бр.39, Гостивар"
  },
  {
    "id": "secondary-021",
    "type": "secondary",
    "municipality": "Гостивар",
    "name": "СМОУ „Гостивар“",
    "address": "ул. „Ристо Оџаклиески“ бр.7-a, Гостивар"
  },
  {
    "id": "secondary-022",
    "type": "secondary",
    "municipality": "град Скопје",
    "name": "СУГС Гимназија „Раде Јовчевски Корчагин“",
    "address": "ул. „Трета Македонска Ударна Бригада“ бр.9, Град Скопје"
  },
  {
    "id": "secondary-023",
    "type": "secondary",
    "municipality": "град Скопје",
    "name": "СУГС Гимназија „Никола Карев“",
    "address": "ул. „Никола Русински“ бб, Град Скопје"
  },
  {
    "id": "secondary-024",
    "type": "secondary",
    "municipality": "град Скопје",
    "name": "СУГС Гимназија „Зеф Љуш Марку“",
    "address": "ул. „Лазо Трповски“ бб, Град Скопје"
  },
  {
    "id": "secondary-025",
    "type": "secondary",
    "municipality": "град Скопје",
    "name": "СУГС Гимназија„Јосип Броз Тито“",
    "address": "ул. „Димитрије Чуповски“ бб, Град Скопје"
  },
  {
    "id": "secondary-026",
    "type": "secondary",
    "municipality": "град Скопје",
    "name": "СУГС Гимназија„Орце Николов“",
    "address": "ул. „Илинденска“ бб, Град Скопје"
  },
  {
    "id": "secondary-027",
    "type": "secondary",
    "municipality": "град Скопје",
    "name": "СУГС „Кочо Рацин“",
    "address": "ул. „Лихнида“ бб, Град Скопје"
  },
  {
    "id": "secondary-028",
    "type": "secondary",
    "municipality": "град Скопје",
    "name": "СУГС „Панче Арсовски“",
    "address": "ул. „Автокоманда“ бб, Град Скопје"
  },
  {
    "id": "secondary-029",
    "type": "secondary",
    "municipality": "град Скопје",
    "name": "СУГС „Браќа Миладиновци“",
    "address": "ул. „Китка“ бб, Град Скопје"
  },
  {
    "id": "secondary-030",
    "type": "secondary",
    "municipality": "град Скопје",
    "name": "СУГС „Георги Димитров“",
    "address": "ул. „Париска“ бр.6-б, Град Скопје"
  },
  {
    "id": "secondary-031",
    "type": "secondary",
    "municipality": "град Скопје",
    "name": "СМУГС „Д-р Панче Караѓозов“",
    "address": "ул. „Водњанска“ бб, Град Скопје"
  },
  {
    "id": "secondary-032",
    "type": "secondary",
    "municipality": "град Скопје",
    "name": "СЕПУГС „Васил Антевски Дрен“",
    "address": "ул. „Вера Јоциќ“ бб, Град Скопје"
  },
  {
    "id": "secondary-033",
    "type": "secondary",
    "municipality": "град Скопје",
    "name": "СЕПУГС „Арсени Јовков“",
    "address": "ул. „Цветан Димов“ бр.17, Град Скопје"
  },
  {
    "id": "secondary-034",
    "type": "secondary",
    "municipality": "град Скопје",
    "name": "СУГС „Цветан Димов“",
    "address": "ул. „Џон Кенеди“ бр.16, Град Скопје"
  },
  {
    "id": "secondary-035",
    "type": "secondary",
    "municipality": "град Скопје",
    "name": "СУГС „Лазар Танев“",
    "address": "ул. „Стрезово“ бб, Град Скопје"
  },
  {
    "id": "secondary-036",
    "type": "secondary",
    "municipality": "град Скопје",
    "name": "СУГС „Марија Кири Склодовска“",
    "address": "ул. „Трета Македонска Бригада“ бр.63, Град Скопје"
  },
  {
    "id": "secondary-037",
    "type": "secondary",
    "municipality": "град Скопје",
    "name": "СГГУГС „Здравко Цветковски“",
    "address": "бул. „Партизански одреди“ бр.91, Град Скопје"
  },
  {
    "id": "secondary-038",
    "type": "secondary",
    "municipality": "град Скопје",
    "name": "СУГС „8 Септември“",
    "address": "бул. „Александар Македонски“ бр.24, Град Скопје"
  },
  {
    "id": "secondary-039",
    "type": "secondary",
    "municipality": "град Скопје",
    "name": "СУГС „Владо Тасевски“",
    "address": "ул. „Трета Македонска Бригада“ бб, Град Скопје"
  },
  {
    "id": "secondary-040",
    "type": "secondary",
    "municipality": "град Скопје",
    "name": "АСУЦ „Боро Петрушевски “ на ГС",
    "address": "бул. „Александар Македонски“ бр.266, Град Скопје"
  },
  {
    "id": "secondary-041",
    "type": "secondary",
    "municipality": "град Скопје",
    "name": "СУГС „Димитар Влахов“",
    "address": "ул. „Трета Македонска Бригада“ бр.22, Град Скопје"
  },
  {
    "id": "secondary-042",
    "type": "secondary",
    "municipality": "град Скопје",
    "name": "СЕТУГС „Михајло Пупин“",
    "address": "ул. „Благоја Стевков“ бб, Град Скопје"
  },
  {
    "id": "secondary-043",
    "type": "secondary",
    "municipality": "град Скопје",
    "name": "СУГС „Шаип Јусуф“",
    "address": "ул. „Вашингтонска“ бр.44, Шуто Оризари"
  },
  {
    "id": "secondary-044",
    "type": "secondary",
    "municipality": "град Скопје",
    "name": "СУГС  „Сарај“",
    "address": "ул. 2 бр.20 Сарај"
  },
  {
    "id": "secondary-045",
    "type": "secondary",
    "municipality": "Дебар",
    "name": "СОУ „28 Ноември“",
    "address": "ул. „Урфи Аголи“ бр.5, Дебар"
  },
  {
    "id": "secondary-046",
    "type": "secondary",
    "municipality": "Делчево",
    "name": "СОУ „Методија Митевски Брицо“",
    "address": "бул. „Методија Митевски Брицо“ бб, Делчево"
  },
  {
    "id": "secondary-047",
    "type": "secondary",
    "municipality": "Демир Хисар",
    "name": "СОУ„Крсте Петков Мисирков“",
    "address": "ул. „Гоце Делчев“ бб, Демир Хисар"
  },
  {
    "id": "secondary-048",
    "type": "secondary",
    "municipality": "Долнени",
    "name": "СОУ „Преродба Рилиндја“",
    "address": "с. Житоше Долнени"
  },
  {
    "id": "secondary-049",
    "type": "secondary",
    "municipality": "Илинден",
    "name": "ССОУ „Илинден“",
    "address": "ул. „Трајко Кошевски“ бб, Штип"
  },
  {
    "id": "secondary-050",
    "type": "secondary",
    "municipality": "Кавадарци",
    "name": "СОУ Гимназија„Добри Даскалов“",
    "address": "ул. „Мито Хаџи Василев“ бр.98, Кавадарци"
  },
  {
    "id": "secondary-051",
    "type": "secondary",
    "municipality": "Кавадарци",
    "name": "СОУ „Киро Спанџов Брко“",
    "address": "ул. „Шишка“ бб, Кавадарци"
  },
  {
    "id": "secondary-052",
    "type": "secondary",
    "municipality": "Кавадарци",
    "name": "СОЗШУ „Ѓорче Петров“",
    "address": "ул. „Шишка“ бр.23, Кавадарци"
  },
  {
    "id": "secondary-053",
    "type": "secondary",
    "municipality": "Кичево",
    "name": "ОСУ „Мирко Милески“",
    "address": "ул. „Рудничка“ бр.2, Кичево"
  },
  {
    "id": "secondary-054",
    "type": "secondary",
    "municipality": "Кичево",
    "name": "ОСУ „Дрита“",
    "address": "ул. „Рудничка“ бр.2, Кичево"
  },
  {
    "id": "secondary-055",
    "type": "secondary",
    "municipality": "Кочани",
    "name": "СОУ „Љупчо Сантов“",
    "address": "ул. „Иво Лола Рибар“ бб, Кочани"
  },
  {
    "id": "secondary-056",
    "type": "secondary",
    "municipality": "Кочани",
    "name": "СОУ „Гошо Викентиев“",
    "address": "ул. „29-ти Ноември“, Кочани"
  },
  {
    "id": "secondary-057",
    "type": "secondary",
    "municipality": "Кратово",
    "name": "СОУ „Митко Пенџуклиски“",
    "address": "ул. „Михајло Апостолски“ бр.10, Кратово"
  },
  {
    "id": "secondary-058",
    "type": "secondary",
    "municipality": "Крива Паланка",
    "name": "СОУ „Ѓорче Петров“",
    "address": "ул. „8-ми Октомври“ бр.91, Крива Паланка"
  },
  {
    "id": "secondary-059",
    "type": "secondary",
    "municipality": "Крушево",
    "name": "СОУ „Наум Наумовски Борче“",
    "address": "ул. „Маршал Тито“ бр.91, Крушево"
  },
  {
    "id": "secondary-060",
    "type": "secondary",
    "municipality": "Куманово",
    "name": "СУГС Гимназија „Гоце Делчев“",
    "address": "ул. „Перо Чичо“ бр.31 а, Куманово"
  },
  {
    "id": "secondary-061",
    "type": "secondary",
    "municipality": "Куманово",
    "name": "ССОУ „Киро Бурназ“",
    "address": "с. Долно Коњари, Куманово"
  },
  {
    "id": "secondary-062",
    "type": "secondary",
    "municipality": "Куманово",
    "name": "СОУ „Перо Наков“",
    "address": "ул. „Моша Пијаде“ бб, Куманово"
  },
  {
    "id": "secondary-063",
    "type": "secondary",
    "municipality": "Куманово",
    "name": "ОСТУ„Наце Буѓони“",
    "address": "ул. „Бајрам Шабани“ Куманово"
  },
  {
    "id": "secondary-064",
    "type": "secondary",
    "municipality": "Куманово",
    "name": "СУГС Гимназија „Сами Фрашери“",
    "address": "бул. ЈНА бб, Куманово"
  },
  {
    "id": "secondary-065",
    "type": "secondary",
    "municipality": "Липково",
    "name": "СОУ „Исмет Јашари“",
    "address": "с. Липково, Липково"
  },
  {
    "id": "secondary-066",
    "type": "secondary",
    "municipality": "Маврово и Ростуша",
    "name": "СОУ „Маврово - Ростуше“",
    "address": "с. Ростуше, Маврово и Ростуша"
  },
  {
    "id": "secondary-067",
    "type": "secondary",
    "municipality": "Македонска Каменица",
    "name": "СОУ „Миле Јаневски Џингар“",
    "address": "ул. „Маршал Тито“ бр.18, Македонска Каменица"
  },
  {
    "id": "secondary-068",
    "type": "secondary",
    "municipality": "Македонски Брод",
    "name": "СОУ „Св.Наум Охридски“",
    "address": "ул. „Партизанска“ бр.22, Македонски Брод"
  },
  {
    "id": "secondary-069",
    "type": "secondary",
    "municipality": "Неготино",
    "name": "СОУ „Св. Кирил и Методиј“",
    "address": "ул. „Индустриска“ бб, Неготино"
  },
  {
    "id": "secondary-070",
    "type": "secondary",
    "municipality": "Охрид",
    "name": "ОСУ „Св.Климент Охридски“",
    "address": "ул. „Димитар Влахов“ бр.71, Охрид"
  },
  {
    "id": "secondary-071",
    "type": "secondary",
    "municipality": "Охрид",
    "name": "СОСУ „Св.Кирил и Мeтодиј“",
    "address": "ул. „Мите Богоевски“ бр.2, Охрид"
  },
  {
    "id": "secondary-072",
    "type": "secondary",
    "municipality": "Охрид",
    "name": "ОЕМУЦ „Св. Наум Охридски“",
    "address": "ул. „15-ти Корпус“ бр.1, Охрид"
  },
  {
    "id": "secondary-073",
    "type": "secondary",
    "municipality": "Охрид",
    "name": "ОУТУ „Ванчо Питошески“",
    "address": "Кеј Маршал Тито бр.101, Охрид"
  },
  {
    "id": "secondary-074",
    "type": "secondary",
    "municipality": "Прилеп",
    "name": "СОУ Гимназија „Мирче Ацев“",
    "address": "ул. „Марксова“ бр.96, Прилеп"
  },
  {
    "id": "secondary-075",
    "type": "secondary",
    "municipality": "Прилеп",
    "name": "СОУ „Ѓорче Петров“",
    "address": "ул. „Октомвриска“ бб, Прилеп"
  },
  {
    "id": "secondary-076",
    "type": "secondary",
    "municipality": "Прилеп",
    "name": "СОУ „Орде Чопела“",
    "address": "ул. „Самоилова“ бб, Прилеп"
  },
  {
    "id": "secondary-077",
    "type": "secondary",
    "municipality": "Прилеп",
    "name": "СОЕПТУ „Кузман Јосифовски Питу“",
    "address": "ул. „Иво Лола Рибар“ бб, Прилеп"
  },
  {
    "id": "secondary-078",
    "type": "secondary",
    "municipality": "Прилеп",
    "name": "СОУ „Ристе Ристески - Ричко“",
    "address": "ул. „Точила“ бб, Прилеп"
  },
  {
    "id": "secondary-079",
    "type": "secondary",
    "municipality": "Пробиштип",
    "name": "СОУ „Наум Наумовски Борче“",
    "address": "ул. „Гоце Делчев“ бр.10, Пробиштип"
  },
  {
    "id": "secondary-080",
    "type": "secondary",
    "municipality": "Радовиш",
    "name": "СОУ „Коста Сусинов“",
    "address": "ул. „8-ми Септември“ бб, Радовиш"
  },
  {
    "id": "secondary-081",
    "type": "secondary",
    "municipality": "Ресен",
    "name": "СОУ „Цар Самоил“",
    "address": "ул. „Кочо Рацин“ бр.48, Ресен"
  },
  {
    "id": "secondary-082",
    "type": "secondary",
    "municipality": "Св. Николе",
    "name": "СОУ „Кочо Рацин“",
    "address": "ул. „Кочо Рацин“ бр.24, Св. Николе"
  },
  {
    "id": "secondary-083",
    "type": "secondary",
    "municipality": "Скопје",
    "name": "ДМБУЦ „Илија Николовски Луј“",
    "address": "ул. „Питу Гули“ бр.1, Скопје"
  },
  {
    "id": "secondary-084",
    "type": "secondary",
    "municipality": "Скопје",
    "name": "ДСУЛУД „Лазар Личеноски“",
    "address": "ул. „Киро Крстевски Платник“ бр.15, Скопје"
  },
  {
    "id": "secondary-085",
    "type": "secondary",
    "municipality": "Скопје",
    "name": "ДУФК „Методија Митевски Брицо“",
    "address": "ул. „Железничка“ бб, Скопје"
  },
  {
    "id": "secondary-086",
    "type": "secondary",
    "municipality": "Скопје",
    "name": "ДУЦОР„Партенија Зографски“",
    "address": "ул. „Благоја Стефковски“ бб, Скопје"
  },
  {
    "id": "secondary-087",
    "type": "secondary",
    "municipality": "Скопје",
    "name": "ДУРДМОВ „Димитар Влахов“",
    "address": "ул. „Ѓорѓи Димитров“ бб, Скопје"
  },
  {
    "id": "secondary-088",
    "type": "secondary",
    "municipality": "Скопје",
    "name": "ДСУРО „Св. Наум Охридски“",
    "address": "ул. „Васил Ѓоргов“ бр.47, Скопје"
  },
  {
    "id": "secondary-089",
    "type": "secondary",
    "municipality": "Скопје",
    "name": "Математичко информатичка гимназија",
    "address": "бул. „Партизански одреди“ бр.91, Скопје"
  },
  {
    "id": "secondary-090",
    "type": "secondary",
    "municipality": "Скопје",
    "name": "Спортска академија",
    "address": "ул. „Железничка“ бб, Скопје"
  },
  {
    "id": "secondary-091",
    "type": "secondary",
    "municipality": "Струга",
    "name": "СОУ „Нико Нестор“",
    "address": "ул. „Пролетерски Бригади“ бр.49, Струга"
  },
  {
    "id": "secondary-092",
    "type": "secondary",
    "municipality": "Струга",
    "name": "СОУ Гимназија  „Д-р Ибрахим Темо“",
    "address": "ул. „Пролетерски Бригади“ бр.49, Струга"
  },
  {
    "id": "secondary-093",
    "type": "secondary",
    "municipality": "Струмица",
    "name": "СОУ „Јане Сандански“",
    "address": "ул. „Моша Пијаде“ бр.2, Струмица"
  },
  {
    "id": "secondary-094",
    "type": "secondary",
    "municipality": "Струмица",
    "name": "СОУ „Никола Карев“",
    "address": "ул. „Маршал Тито“ бр.170, Струмица"
  },
  {
    "id": "secondary-095",
    "type": "secondary",
    "municipality": "Струмица",
    "name": "СОУ „Димитар Влахов“",
    "address": "ул. „Димитар Хаџи Василев“ бр.26, Струмица"
  },
  {
    "id": "secondary-096",
    "type": "secondary",
    "municipality": "Тетово",
    "name": "СОУ Гимназија „Кирил Пејчиновиќ“",
    "address": "ул. „Браќа Миладиновци“ бр.134, Тетово"
  },
  {
    "id": "secondary-097",
    "type": "secondary",
    "municipality": "Тетово",
    "name": "СОУ Гимназија „7 Марси“",
    "address": "населба Дреноец, Тетово"
  },
  {
    "id": "secondary-098",
    "type": "secondary",
    "municipality": "Тетово",
    "name": "СОМУ„Никола Штејн“",
    "address": "ул. „Ѓорче Петров“ бр. 23, Тетово"
  },
  {
    "id": "secondary-099",
    "type": "secondary",
    "municipality": "Тетово",
    "name": "ОСЕУ „8 Септември“",
    "address": "ул. „Борис Кидрич“ бб, Тетово"
  },
  {
    "id": "secondary-100",
    "type": "secondary",
    "municipality": "Тетово",
    "name": "СОСУ „Моша Пијаде“",
    "address": "ул. „Илиденска“ бб, Тетово"
  },
  {
    "id": "secondary-101",
    "type": "secondary",
    "municipality": "Тетово",
    "name": "СОТУ „Ѓоце Стојчески“",
    "address": "ул. „Браќа Миладиновци“ бр.169, Тетово"
  },
  {
    "id": "secondary-102",
    "type": "secondary",
    "municipality": "Тетово",
    "name": "ДМУ „Тодор Скаловски -Тетоец“",
    "address": "ул. „Иво Лола Риба“ бр.118, Тетово"
  },
  {
    "id": "secondary-103",
    "type": "secondary",
    "municipality": "Центар Жупа",
    "name": "СОУ „АТА“",
    "address": "ул.б.б Центар Жупа"
  },
  {
    "id": "secondary-104",
    "type": "secondary",
    "municipality": "Штип",
    "name": "СОУ „Славчо Стојменски“",
    "address": "ул. „Васил Главинов“ бр.4, Штип"
  },
  {
    "id": "secondary-105",
    "type": "secondary",
    "municipality": "Штип",
    "name": "СОУ „Коле Нехтенин“",
    "address": "ул. „Гоце Делчев“ бр.101, Штип"
  },
  {
    "id": "secondary-106",
    "type": "secondary",
    "municipality": "Штип",
    "name": "СОУ „Димитар Мирасчиев“",
    "address": "ул. „Вита Поп-Јорданова“ бр.2, Штип"
  },
  {
    "id": "secondary-107",
    "type": "secondary",
    "municipality": "Штип",
    "name": "СОУ „Јане Сандански“",
    "address": "ул. „Трајко Кошевски“ бб, Штип"
  },
  {
    "id": "secondary-108",
    "type": "secondary",
    "municipality": "Штип",
    "name": "ДМУЦ „Сергеј Михајлов“",
    "address": "ул. „Рајко Жинзифов“ бр.5, Штип"
  },
  {
    "id": "secondary-109",
    "type": "secondary",
    "municipality": "Штип",
    "name": "ДСУОР „Искра“",
    "address": "ул. „Рибник“ бр.14, Штип"
  },
  {
    "id": "vet-001",
    "type": "vet",
    "municipality": "Куманово",
    "name": "ДСУ РЦСОО „Киро Бурназ“",
    "city": "Куманово",
    "website": "https://kiroburnaz.edu.mk/"
  },
  {
    "id": "vet-002",
    "type": "vet",
    "municipality": "Охрид",
    "name": "ДСУ РЦСОО „Ванчо Питошески“",
    "city": "Охрид",
    "website": "https://vancopitoseski.edu.mk/"
  },
  {
    "id": "vet-003",
    "type": "vet",
    "municipality": "Тетово",
    "name": "ДСУ РЦСОО „Моша Пијаде“",
    "city": "Тетово",
    "website": "https://mosapijade.te.mk/"
  },
  {
    "id": "vet-004",
    "type": "vet",
    "municipality": "Велес",
    "name": "ДСУ РЦСОО „Коле Неделковски“",
    "city": "Велес",
    "website": "https://kolenedelkovski.edu.mk/"
  },
  {
    "id": "vet-005",
    "type": "vet",
    "municipality": "Струмица",
    "name": "ДСУ РЦСОО „Никола Карев“",
    "city": "Струмица",
    "website": "https://nkarev-strumica.edu.mk/"
  },
  {
    "id": "vet-006",
    "type": "vet",
    "municipality": "Битола",
    "name": "ДСУ РЦСОО „Ѓорѓи Наумов“",
    "city": "Битола",
    "website": "https://gorginaumov.edu.mk/"
  },
  {
    "id": "vet-007",
    "type": "vet",
    "municipality": "Штип",
    "name": "ДСУ РЦСОО „Коле Нехтенин“",
    "city": "Штип",
    "website": "https://kolenehtenin.edu.mk/"
  }
];
